'use strict';

const DATA_HOME = [
  {
    id: 'home-01', circuitNum: '01',
    title: 'PUSH + CORE', subtitle: 'chest - shoulders - core',
    muscles: ['chest','shoulders','core'],
    illustration: 'pushups.svg',
    duration: 35, rounds: 3,
    exercises: [
      { id: 'wide-pushup', name: 'Wide Push-Ups', muscles: ['chest','shoulders'],
        baseReps: 12, baseRest: 60, unit: 'reps',
        variations: [{ minLevel:1, name:'Wide Push-Ups' },{ minLevel:4, name:'Archer Push-Ups' },{ minLevel:6, name:'Ring Archer Push-Ups' }],
        form: { setup: 'Place hands wider than shoulder-width, fingers pointing slightly outward. Feet together or hip-width. Body forms a straight plank from heels to crown — no hips sagging, no butt in the air.', execution: 'Lower your chest toward the floor by bending the elbows out at roughly 45 degrees. Touch the floor or come within a fist-width. Press back to lockout by driving the floor away.', cue: 'Squeeze the floor inward without moving your hands — this activates your chest fully and keeps shoulders packed.', breathing: 'Inhale on the way down. Exhale forcefully on the push-up phase.', mistakes: 'Flared elbows at 90 degrees. Hips sagging. Partial range — chest must reach depth to count. Head dropped forward.' }},
      { id: 'diamond-pushup', name: 'Diamond Push-Ups', muscles: ['chest','triceps'],
        baseReps: 10, baseRest: 60, unit: 'reps',
        variations: [{ minLevel:1, name:'Diamond Push-Ups' },{ minLevel:4, name:'Close-Grip Ring Push-Ups' }],
        form: { setup: 'Form a diamond shape with thumbs and index fingers touching, hands centered under your sternum. Full plank position.', execution: 'Lower your chest directly to your hands while keeping elbows close to your ribs. Press up to full extension.', cue: 'Try to "break the diamond" apart — this activates the triceps maximally.', breathing: 'Inhale on descent, exhale on the push.', mistakes: 'Hands placed too far forward. Elbows flaring outward. Short range of motion.' }},
      { id: 'decline-pushup', name: 'Decline Push-Ups', muscles: ['chest','shoulders'],
        baseReps: 10, baseRest: 60, unit: 'reps',
        variations: [{ minLevel:1, name:'Decline Push-Ups' },{ minLevel:4, name:'Deficit Decline Push-Ups' }],
        form: { setup: 'Place feet on a chair or couch at 30-45 degrees elevation. Hands at shoulder-width. Full body plank.', execution: 'Lower your forehead toward the floor. Press back up through the upper chest.', cue: 'Pull your shoulder blades together at the top of each rep.', breathing: 'Slow controlled inhale going down. Sharp exhale driving up.', mistakes: 'Hips sagging. Head dropping first. Rushing the eccentric.' }},
      { id: 'pike-pushup', name: 'Pike Push-Ups', muscles: ['shoulders','core'],
        baseReps: 10, baseRest: 60, unit: 'reps',
        variations: [{ minLevel:1, name:'Pike Push-Ups' },{ minLevel:4, name:'Deficit Pike Push-Ups' }],
        form: { setup: 'Start in downward dog — hips high, arms and legs straight, inverted V shape. Hands shoulder-width.', execution: 'Bend elbows to lower the crown of your head toward the floor between your hands. Press back up.', cue: 'Drive your hips up and back as you press.', breathing: 'Inhale on descent, exhale on the press.', mistakes: 'Hips dropping as fatigue hits. Head not reaching depth. Arms too wide.' }},
      { id: 'hollow-body', name: 'Hollow Body Hold', muscles: ['core'],
        baseReps: 30, baseRest: 45, unit: 'sec',
        variations: [{ minLevel:1, name:'Hollow Body Hold' },{ minLevel:4, name:'Hollow Body Rocks' },{ minLevel:6, name:'V-Ups' }],
        form: { setup: 'Lie on back. Press lower back into floor. Arms overhead, legs extended. Lift slightly off floor.', execution: 'Maintain the position. Every second of proper position counts.', cue: 'Exhale all air and crush belly button toward spine.', breathing: 'Short controlled breaths — exhale helps maintain hollow.', mistakes: 'Lower back arching off floor. Arms held too low. Holding breath.' }},
      { id: 'plank-k2e', name: 'Plank Knee-to-Elbow', muscles: ['core','obliques'],
        baseReps: 16, baseRest: 45, unit: 'reps',
        variations: [{ minLevel:1, name:'Plank Knee-to-Elbow' },{ minLevel:4, name:'Plank Knee-to-Elbow 3s Tempo' }],
        form: { setup: 'High plank — arms straight, hands below shoulders. Body rigid. Feet hip-width. Engage core.', execution: 'Drive one knee toward same-side elbow, rotating at the oblique. Return to plank. Alternate sides.', cue: 'Think of trying to bring your hip to your armpit.', breathing: 'Exhale as you drive the knee in. Inhale as you return.', mistakes: 'Hips rising into a pike. Letting the planted foot drag. Moving too fast.' }},
      { id: 'dead-bug', name: 'Dead Bug', muscles: ['core'],
        baseReps: 16, baseRest: 45, unit: 'reps',
        variations: [{ minLevel:1, name:'Dead Bug' },{ minLevel:4, name:'Dead Bug with Band Resistance' }],
        form: { setup: 'Lie on back. Arms vertical. Hips and knees at 90 degrees. Press lower back firmly into floor.', execution: 'Simultaneously lower opposite arm overhead and opposite leg toward floor. Return. Alternate.', cue: 'Imagine a string pulling your navel toward the floor.', breathing: 'Exhale fully as you extend. Inhale to return.', mistakes: 'Lower back lifting. Moving both limbs on same side. Rushing.' }}
    ]
  },
  {
    id: 'home-02', circuitNum: '02',
    title: 'PULL + BICEPS', subtitle: 'back - biceps - grip',
    muscles: ['back','biceps','grip'],
    illustration: 'pullups.svg',
    duration: 35, rounds: 3,
    exercises: [
      { id: 'pullup', name: 'Pull-Ups', muscles: ['back','biceps','grip'],
        baseReps: 5, baseRest: 90, unit: 'reps',
        variations: [{ minLevel:1, name:'Pull-Ups' },{ minLevel:4, name:'Pull-Ups 4s Negative' },{ minLevel:6, name:'Typewriter Pull-Ups' }],
        form: { setup: 'Hang from bar with pronated grip, hands just outside shoulder-width. Full dead hang. No swinging.', execution: 'Pull elbows down and back, driving chest toward bar. Clear bar with chin. Lower to dead hang.', cue: 'Think "elbows to your back pockets" — engages lats, prevents bicep-dominant cheat pull.', breathing: 'Exhale on the pull up. Inhale on the controlled descent.', mistakes: 'Partial range. Kipping when strength is the goal. Shrugging at top. Rushing the descent.' }},
      { id: 'widegrip-pullup', name: 'Wide-Grip Pull-Ups', muscles: ['back','grip'],
        baseReps: 4, baseRest: 90, unit: 'reps',
        variations: [{ minLevel:1, name:'Wide-Grip Pull-Ups' },{ minLevel:4, name:'Wide-Grip 3s Pause at Top' }],
        form: { setup: 'Hands 1.5-2x shoulder-width pronated. Initiate with shoulder pack — blades together and down.', execution: 'Drive elbows down and wide. Chest leads toward bar. Hold top briefly. Lower slowly.', cue: 'At the top, try to bend the bar — flares lats and locks in maximum contraction.', breathing: 'Sharp exhale at initiation. Slow inhale on descent.', mistakes: 'Arms too wide. Chin-leading instead of chest-leading. No shoulder pack at start.' }},
      { id: 'chinup', name: 'Chin-Ups', muscles: ['biceps','back'],
        baseReps: 6, baseRest: 75, unit: 'reps',
        variations: [{ minLevel:1, name:'Chin-Ups' },{ minLevel:4, name:'Chin-Ups 4s Negative' },{ minLevel:6, name:'Weighted Chin-Ups' }],
        form: { setup: 'Supinated grip, hands shoulder-width or narrower. Full dead hang start.', execution: 'Pull until chin clears bar. Lower with deliberate control to complete dead hang.', cue: 'At the bottom of each rep, flex biceps consciously before pulling again.', breathing: 'Exhale pulling up, inhale going down.', mistakes: 'Head jutting forward to clear bar. Not reaching full hang. Swinging hips.' }},
      { id: 'iso-chin-hold', name: 'Isometric Chin Hold', muscles: ['biceps','back','grip'],
        baseReps: 3, baseRest: 60, unit: 'reps', tempo: '8s hold',
        variations: [{ minLevel:1, name:'Isometric Chin Hold 5s' },{ minLevel:4, name:'Isometric Chin Hold 8s + Super-Slow Negative' }],
        form: { setup: 'Chin-up grip. Pull to top position with chin over bar. Pause.', execution: 'Hold top position for prescribed time. Lower with super-slow controlled negative (8s).', cue: 'Actively squeeze bar, flex lats, press upper arms toward torso simultaneously.', breathing: 'Breathe carefully while holding. Exhale gradually during descent.', mistakes: 'Hanging passively at top. Descent becoming uncontrolled. Holding breath entire time.' }},
      { id: 'band-row', name: 'Band Row', muscles: ['back','biceps'],
        baseReps: 15, baseRest: 60, unit: 'reps',
        variations: [{ minLevel:1, name:'Band Row' }],
        form: { setup: 'Hold band in both hands anchored under feet. Hinge forward 45 degrees. Core braced, back flat.', execution: 'Pull band toward lower ribcage, driving elbows back, squeezing shoulder blades together at end.', cue: 'Lead the pull with your elbow, not your hand. Hands are hooks — elbow is the engine.', breathing: 'Exhale on the pull, inhale on the return.', mistakes: 'Rounding the lower back. Standing up during set. Not squeezing shoulder blades at end range.' }},
      { id: 'dead-hang', name: 'Dead Hang', muscles: ['grip','forearms','fingers'],
        baseReps: 45, baseRest: 60, unit: 'sec',
        variations: [{ minLevel:1, name:'Dead Hang' },{ minLevel:4, name:'Dead Hang 3-Grip Rotation' }],
        form: { setup: 'Grab bar with overhand grip. Relax to full hang, then pack shoulders down. Find active hang.', execution: 'Simply hang. For rotation: alternate overhand, neutral, underhand every 15 seconds.', cue: 'Try to "bend" the bar apart — activates lats passively, makes this a full back exercise.', breathing: 'Normal rhythmic breathing. Manage breath to stay relaxed.', mistakes: 'Passive hang with no shoulder engagement. Clenching jaw and neck.' }}
    ]
  },
  {
    id: 'home-03', circuitNum: '03',
    title: 'LEGS + BODY', subtitle: 'legs - glutes - core',
    muscles: ['legs','glutes','core'],
    illustration: 'squats.svg',
    duration: 35, rounds: 3,
    exercises: [
      { id: 'bulgarian-split', name: 'Bulgarian Split Squat', muscles: ['legs','glutes'],
        baseReps: 10, baseRest: 75, unit: 'reps', note: 'Per leg',
        variations: [{ minLevel:1, name:'Bulgarian Split Squat' },{ minLevel:4, name:'KB Bulgarian Split Squat' },{ minLevel:6, name:'TRX Pistol Squat' }],
        form: { setup: 'Rear foot elevated on chair, knee height. Front foot far enough forward that shin stays vertical.', execution: 'Lower rear knee toward floor bending front knee and hip. Keep torso upright. Press through front heel to return.', cue: 'On the way up, think "drive the floor down through my heel."', breathing: 'Inhale on descent, exhale on the drive up.', mistakes: 'Front shin going far past toes. Torso collapsing forward. Rear knee banging floor.' }},
      { id: 'squat-pulse', name: 'Squat Pulse', muscles: ['legs','glutes'],
        baseReps: 20, baseRest: 60, unit: 'reps',
        variations: [{ minLevel:1, name:'Squat Pulse' },{ minLevel:4, name:'Jump Squats' }],
        form: { setup: 'Feet shoulder-width, toes slightly out. Hands clasped in front. Brace core.', execution: 'Lower to parallel or below. At bottom, perform small pulses (5-10cm) for prescribed count.', cue: 'Keep chest up and knees tracking over toes. The burn is the point.', breathing: 'Rhythmic breathing in pulse position. Short controlled breaths.', mistakes: 'Heels lifting. Knees caving inward. Sitting up between pulses.' }},
      { id: 'band-good-morning', name: 'Band Good Mornings', muscles: ['legs','glutes','back'],
        baseReps: 15, baseRest: 60, unit: 'reps',
        variations: [{ minLevel:1, name:'Band Good Mornings' }],
        form: { setup: 'Stand on band center, loop around neck/shoulders. Slight knee bend, back flat.', execution: 'Hinge at hips — push hips back keeping back straight and chest tall. Lower until strong hamstring stretch.', cue: 'Hinge, do not bend. Chest stays proud and back flat throughout.', breathing: 'Inhale on the hinge back, exhale as you drive hips forward.', mistakes: 'Rounding lower back at bottom. Bending knees too much. Not going deep enough.' }},
      { id: 'russian-twist', name: 'Russian Twists', muscles: ['core','obliques'],
        baseReps: 20, baseRest: 45, unit: 'reps',
        variations: [{ minLevel:1, name:'Russian Twists' },{ minLevel:4, name:'Weighted Russian Twists' }],
        form: { setup: 'Sit on floor. Lean torso back 45 degrees. Feet elevated 30cm. Arms extended forward.', execution: 'Rotate torso side to side, touching floor beside each hip. One left + one right = one rep.', cue: 'Rotate from the ribs, not the arms. Feel the side of your torso twisting.', breathing: 'Exhale on each twist. Short punchy breaths.', mistakes: 'Torso coming upright between reps. Moving only arms without trunk rotation.' }},
      { id: 'glute-bridge', name: 'Glute Bridge Hold', muscles: ['glutes','core'],
        baseReps: 12, baseRest: 45, unit: 'reps',
        variations: [{ minLevel:1, name:'Glute Bridge Hold' },{ minLevel:4, name:'Single-Leg Glute Bridge' }],
        form: { setup: 'Lie on back. Feet hip-width flat on floor, heels 30cm from glutes. Arms at sides.', execution: 'Drive through heels to lift hips until straight line from knees to shoulders. Squeeze glutes at top. Hold 2 counts.', cue: 'Dig heels into floor and try to drag them toward glutes — fires hamstrings as synergist.', breathing: 'Exhale on the lift, inhale on the descent.', mistakes: 'Hips not reaching full extension. Knees falling outward. Dropping hips too quickly.' }}
    ]
  }
];
