// =============================================================================
// data-home.ts — HOME mode: 40-minute sessions with a mat, a pull-up bar and a band
//
// Three sessions, each with one job:
//   01 TENSION — body tension and trunk. The cheapest gains available at home.
//   02 PULL    — pulling strength. The measured limiter for this athlete.
//   03 ARMOUR  — antagonists, elbow and shoulder resilience, legs, hip mobility.
//
// None of these load the fingers maximally, so any of them can sit 24h after a
// hard gym or climbing day without competing for tendon recovery.
// =============================================================================

import type { Circuit } from './types';

const HOME_WARMUP = {
  id: 'home-warmup',
  name: 'Warm-Up Flow',
  capacities: ['mobility' as const, 'shoulder' as const],
  block: 'WARMUP' as const, intensity: 'EASY' as const,
  sets: 1, work: 300, unit: 'sec' as const, restSec: 30,
  load: { kind: 'bodyweight' as const, text: 'No load' },
  fixed: true,
  progression: 'Never progressed.',
  protocolId: 'warmup',
  note: 'Pulse raiser, shoulder circles, band external rotations, scapular pull-ups, dead hang.',
  form: {
    setup: 'Mat down, band to hand, bar available.',
    execution: 'Two minutes raising the pulse. Ten shoulder circles each direction, 15 band external rotations per side, 10 scapular pull-ups, 20s relaxed dead hang.',
    cue: 'Five minutes now buys you the session. It also tells you how the body actually feels today.',
    breathing: 'Nasal and unhurried.',
    mistakes: 'Starting the first working set cold because the session is short.',
  },
};

export const DATA_HOME: Circuit[] = [
  {
    id: 'home-01', circuitNum: '01',
    title: 'TENSION', subtitle: 'body tension - trunk',
    focus: 'Hold a line from hands to feet on steep ground.',
    capacities: ['tension', 'pull'],
    illustration: 'pullups.svg',
    duration: 45,
    recoveryHours: 24,
    note: 'Every hold ends when the lower back arches, not when the timer does.',
    exercises: [
      HOME_WARMUP,
      {
        id: 'home-front-lever',
        name: 'Front Lever Progression',
        capacities: ['tension', 'pull'],
        block: 'PRIMARY', intensity: 'HARD',
        sets: 5, work: 10, unit: 'sec', restSec: 120,
        load: { kind: 'bodyweight', text: 'Hardest progression held with a flat lower back' },
        progression: 'Five clean sets of 12s, then move up a progression and reset to 8s.',
        protocolId: 'tension-iso',
        variations: [
          { minLevel: 1, name: 'Tuck Front Lever' },
          { minLevel: 3, name: 'Advanced Tuck Front Lever' },
          { minLevel: 5, name: 'One-Leg Front Lever' },
          { minLevel: 6, name: 'Straddle Front Lever' },
          { minLevel: 7, name: 'Full Front Lever' },
        ],
        form: {
          setup: 'Hang from the bar, arms straight, shoulders depressed.',
          execution: 'Pull to horizontal in your progression and hold. Lower back flat, ribs down, glutes on, pelvis tucked.',
          cue: 'Push the bar away with straight arms rather than pulling with bent ones. This is a lat and trunk exercise, not an arm exercise.',
          breathing: 'Short controlled breaths. Do not hold your breath for ten seconds.',
          mistakes: 'Arching the back to make it easier. Bending the arms. Skipping ahead a progression before the current one is solid.',
        },
      },
      {
        id: 'home-leg-raise',
        name: 'Hanging Leg Raise',
        capacities: ['tension'],
        block: 'SECONDARY', intensity: 'HARD',
        sets: 4, work: 8, unit: 'reps', restSec: 90,
        load: { kind: 'bodyweight', text: 'Bodyweight, slow and controlled' },
        progression: 'Knees to chest, then straight legs to horizontal, then toes to bar, then slow lowering with a 3s eccentric.',
        protocolId: 'tension-iso',
        variations: [
          { minLevel: 1, name: 'Hanging Knee Raise' },
          { minLevel: 3, name: 'Hanging Straight Leg Raise' },
          { minLevel: 5, name: 'Toes to Bar' },
          { minLevel: 6, name: 'Toes to Bar with 3s Lower' },
        ],
        form: {
          setup: 'Dead hang, shoulders packed before the first rep.',
          execution: 'Raise the legs under control, pause at the top, lower slowly without swinging. Reset the swing before the next rep rather than using it.',
          cue: 'Hip flexor strength with a locked trunk is what keeps your feet on the wall when it steepens. Speed defeats the purpose.',
          breathing: 'Exhale on the way up.',
          mistakes: 'Swinging into each rep. Letting the shoulders go passive at the bottom.',
        },
      },
      {
        id: 'home-hollow-arch',
        name: 'Hollow Hold / Arch Hold',
        capacities: ['tension'],
        block: 'SECONDARY', intensity: 'MODERATE',
        sets: 3, work: 30, unit: 'sec', restSec: 60,
        load: { kind: 'bodyweight', text: 'Bodyweight' },
        progression: 'Extend the arms and legs further, then add time to 45s, then add a light weight overhead.',
        protocolId: 'tension-iso',
        note: 'Alternate: one set hollow on the back, one set arch face down.',
        form: {
          setup: 'On your back for hollow, face down for arch.',
          execution: 'Hollow: lower back pressed flat into the floor, arms and legs extended and lifted. Arch: chest and thighs lifted, glutes engaged.',
          cue: 'Training both sides of the trunk keeps the front-lever line balanced. Most climbers train the hollow and skip the arch.',
          breathing: 'Short breaths, exhale to hold the hollow position.',
          mistakes: 'Lower back lifting off the floor in the hollow. Cranking the neck in the arch.',
        },
      },
      {
        id: 'home-pallof',
        name: 'Band Pallof Press',
        capacities: ['tension'],
        block: 'ACCESSORY', intensity: 'MODERATE',
        sets: 3, work: 10, unit: 'reps', restSec: 60,
        load: { kind: 'band', text: 'Band anchored at chest height' },
        progression: 'Step further from the anchor, then add an overhead press at the end range.',
        protocolId: 'tension-iso',
        perSide: true,
        form: {
          setup: 'Band anchored at chest height, stand side-on, hands at the sternum, feet shoulder width.',
          execution: 'Press the hands straight out and hold for two seconds while the band tries to rotate you. Return under control.',
          cue: 'Anti-rotation. The trunk resists twisting while the arms move — exactly what happens on a hard reach off a bad foot.',
          breathing: 'Exhale on the press.',
          mistakes: 'Letting the torso rotate. Using a band so heavy the hips have to counterbalance.',
        },
      },
      {
        id: 'home-copenhagen',
        name: 'Copenhagen Plank',
        capacities: ['tension', 'legs'],
        block: 'ACCESSORY', intensity: 'MODERATE',
        sets: 3, work: 20, unit: 'sec', restSec: 60,
        load: { kind: 'bodyweight', text: 'Bodyweight' },
        progression: 'Bent knee on the support, then the full straight-leg version, then add time to 30s.',
        protocolId: 'tension-iso',
        perSide: true,
        note: 'Adductor strength. Drop knees, bridging and knee health all live here.',
        form: {
          setup: 'Side plank on the forearm, top leg resting on a chair or bench at knee or ankle height.',
          execution: 'Lift the hips so the body is a straight line, with the bottom leg lifted toward the top one. Hold.',
          cue: 'The adductors do a lot of work in climbing and almost never get trained directly. This is the fix.',
          breathing: 'Steady.',
          mistakes: 'Hips sagging. Rolling the chest toward the floor.',
        },
      },
      {
        id: 'home-band-er-01',
        name: 'Band External Rotation',
        capacities: ['shoulder'],
        block: 'PREHAB', intensity: 'EASY',
        sets: 2, work: 15, unit: 'reps', restSec: 45,
        load: { kind: 'band', text: 'Light band — never to failure' },
        progression: 'Reps to 20, then a marginally heavier band.',
        protocolId: 'prehab',
        perSide: true,
        form: {
          setup: 'Band at elbow height, elbow tucked to the ribs at 90 degrees.',
          execution: 'Rotate the forearm outward keeping the elbow pinned, slow return.',
          cue: 'Maintenance for the joint that takes the most abuse in climbing. Light and often beats heavy and occasional.',
          breathing: 'Exhale rotating out.',
          mistakes: 'Elbow drifting off the ribs. Going heavy.',
        },
      },
    ],
  },
  {
    id: 'home-02', circuitNum: '02',
    title: 'PULL', subtitle: 'maximal pulling',
    focus: 'The measured limiter: get the weighted pull-up toward 165% bodyweight.',
    capacities: ['pull', 'shoulder', 'forearm'],
    illustration: 'barbell.svg',
    duration: 42,
    recoveryHours: 24,
    note: 'Heavy and low rep. If you are getting a pump, the load is too light and the reps too many.',
    exercises: [
      HOME_WARMUP,
      {
        id: 'home-weighted-pullup',
        name: 'Weighted Pull-Ups',
        capacities: ['pull'],
        block: 'PRIMARY', intensity: 'MAX',
        sets: 5, work: 4, unit: 'reps', restSec: 150,
        load: { kind: 'added-kg', text: 'RPE 8-9 — 1-2 reps in reserve. A loaded pack works.' },
        progression:
          'Five clean sets of 4, then add 2kg. At 62kg bodyweight, 165% means a working '
          + 'single with +40kg. Anything you add here shows up on the wall.',
        protocolId: 'max-strength',
        variations: [
          { minLevel: 1, name: 'Pull-Ups — Bodyweight' },
          { minLevel: 2, name: 'Pull-Ups — 4s Eccentric' },
          { minLevel: 4, name: 'Weighted Pull-Ups' },
          { minLevel: 6, name: 'Weighted Pull-Ups — Heavy' },
          { minLevel: 7, name: 'One-Arm Pull-Up Progression' },
        ],
        form: {
          setup: 'Dead hang, pronated grip just outside shoulder width. Loaded pack or a belt.',
          execution: 'Pull elbows down and back, chest to the bar, chin clearly over. Lower under control to a full dead hang each rep.',
          cue: 'Elbows to your back pockets. Every rep starts from a real dead hang.',
          breathing: 'Exhale on the pull.',
          mistakes: 'Kipping. Half reps. Picking a weight that turns a strength set into an endurance set.',
        },
      },
      {
        id: 'home-lockoff',
        name: 'Lock-Off Ladder',
        capacities: ['pull'],
        block: 'SECONDARY', intensity: 'HARD',
        sets: 3, work: 15, unit: 'sec', restSec: 120,
        load: { kind: 'bodyweight', text: 'Bodyweight, assisted or weighted' },
        progression: 'Add 2s per position, then go one-armed with the free hand on the wrist, then add weight.',
        protocolId: 'lock-off',
        perSide: true,
        note: '5s at 120 degrees, 5s at 90, 5s at 60. One descent per set.',
        form: {
          setup: 'Pull to the top of the bar, then lower into the first position.',
          execution: 'Five seconds at each of three elbow angles on the way down.',
          cue: 'Ninety degrees is where most climbers fail. Train the angle you fall from.',
          breathing: 'Keep breathing.',
          mistakes: 'Sinking through the positions instead of holding them.',
        },
      },
      {
        id: 'home-row',
        name: 'Inverted Row',
        capacities: ['pull', 'shoulder'],
        block: 'SECONDARY', intensity: 'MODERATE',
        sets: 3, work: 8, unit: 'reps', restSec: 90,
        load: { kind: 'bodyweight', text: 'Body angle sets the load' },
        progression: 'Feet further forward, then feet elevated, then a pack on the chest.',
        protocolId: 'max-strength',
        note: 'Horizontal pulling balances a training week that is otherwise all vertical.',
        form: {
          setup: 'Bar at hip height, or a band under the feet if there is no low bar. Body straight from heels to head.',
          execution: 'Pull the chest to the bar, driving the elbows back and squeezing the shoulder blades together at the end.',
          cue: 'Lead with the elbow, not the hand. The hands are hooks.',
          breathing: 'Exhale on the pull.',
          mistakes: 'Hips sagging. Stopping short of the bar. Shrugging.',
        },
      },
      {
        id: 'home-dead-hang',
        name: 'Dead Hang',
        capacities: ['forearm'],
        block: 'ACCESSORY', intensity: 'MODERATE',
        sets: 3, work: 45, unit: 'sec', restSec: 60,
        load: { kind: 'bodyweight', text: 'Bodyweight on the bar' },
        progression: 'To 60s, then add a small weight rather than more time.',
        note: 'Switch grip every 15s: overhand, then a towel over the bar if you have one.',
        form: {
          setup: 'Bar, shoulders packed and active, not passive.',
          execution: 'Hang for 45 seconds keeping the shoulders engaged throughout.',
          cue: 'Try to bend the bar apart. A passive hang trains skin tolerance and nothing else.',
          breathing: 'Slow and even.',
          mistakes: 'Dead shoulders. Gritting through pain in the fingers rather than the forearms.',
        },
      },
      {
        id: 'home-wrist-armour',
        name: 'Wrist Extensor + Pronator',
        capacities: ['shoulder'],
        block: 'PREHAB', intensity: 'EASY',
        sets: 2, work: 15, unit: 'reps', restSec: 45,
        load: { kind: 'band', text: 'Band or a light household weight' },
        progression: 'Reps to 20, then slightly heavier. Slow lowering throughout.',
        protocolId: 'prehab',
        perSide: true,
        form: {
          setup: 'Forearm resting on the thigh, wrist over the knee, band or weight in hand.',
          execution: 'Fifteen wrist extensions palm-down with a 3s lower, then fifteen slow pronations.',
          cue: 'Climbing loads the flexors relentlessly and the extensors barely at all. Medial elbow pain lives in that gap.',
          breathing: 'Relaxed.',
          mistakes: 'Going heavy and fast. Dropping it from the programme once the elbow stops complaining.',
        },
      },
    ],
  },
  {
    id: 'home-03', circuitNum: '03',
    title: 'ARMOUR', subtitle: 'antagonist - legs - mobility',
    focus: 'Wrists, hips, shoulders. The session that fixes what climbing broke.',
    capacities: ['press', 'shoulder', 'legs', 'mobility'],
    illustration: 'pushups.svg',
    duration: 45,
    recoveryHours: 12,
    note: 'Currently the highest-priority session in the programme: wrists are symptomatic and hip mobility is the stated weakness on slabs. Twice a week, minimum.',
    exercises: [
      HOME_WARMUP,
      {
        id: 'home-pike-press',
        name: 'Pike Push-Up / Band Overhead Press',
        capacities: ['press', 'shoulder'],
        block: 'PRIMARY', intensity: 'HARD',
        sets: 4, work: 8, unit: 'reps', restSec: 90,
        load: { kind: 'bodyweight', text: 'Bodyweight, or band for the press variant' },
        progression: 'Feet elevated, then a deficit under the hands, then toward a wall handstand push-up.',
        protocolId: 'max-strength',
        note: 'Overhead pressing is the single most valuable antagonist movement for a climbing shoulder.',
        variations: [
          { minLevel: 1, name: 'Pike Push-Up' },
          { minLevel: 3, name: 'Feet-Elevated Pike Push-Up' },
          { minLevel: 5, name: 'Deficit Pike Push-Up' },
          { minLevel: 6, name: 'Wall Handstand Push-Up' },
        ],
        form: {
          setup: 'Downward dog, hips high, hands shoulder width, weight shifted forward over the hands.',
          execution: 'Lower the crown of the head toward the floor between the hands, then press back to full extension with the shoulders reaching overhead.',
          cue: 'Finish every rep with the shoulders actively pushing up. Climbers lose overhead range, and losing it is how shoulders start hurting.',
          breathing: 'Inhale down, exhale on the press.',
          mistakes: 'Hips dropping as fatigue arrives, which turns it into a push-up. Not reaching depth.',
        },
      },
      {
        id: 'home-pushup',
        name: 'Push-Ups',
        capacities: ['press'],
        block: 'ACCESSORY', intensity: 'MODERATE',
        sets: 2, work: 12, unit: 'reps', restSec: 60,
        load: { kind: 'bodyweight', text: 'Bodyweight, feet elevated to add load' },
        progression: 'Feet elevated, then a pack on the back, then archer push-ups. Do not chase hypertrophy here.',
        protocolId: 'prehab',
        note: 'Enough pressing to stay balanced. Not enough to build chest mass you then have to carry up the wall.',
        form: {
          setup: 'Hands under the shoulders, body straight from heels to crown.',
          execution: 'Lower the chest to a fist off the floor with elbows at about 45 degrees, press back to lockout.',
          cue: 'Push the floor away and let the shoulder blades spread at the top. That top position is where the serratus works.',
          breathing: 'Inhale down, exhale up.',
          mistakes: 'Elbows flared to 90 degrees. Hips sagging. Adding endless reps in the belief that more is better.',
        },
      },
      {
        id: 'home-split-squat',
        name: 'Bulgarian Split Squat',
        capacities: ['legs'],
        block: 'SECONDARY', intensity: 'MODERATE',
        sets: 3, work: 8, unit: 'reps', restSec: 90,
        load: { kind: 'bodyweight', text: 'Bodyweight, then a loaded pack' },
        progression: 'To 12 reps bodyweight, then add a pack. Strength, not burn.',
        protocolId: 'max-strength',
        perSide: true,
        form: {
          setup: 'Rear foot on a chair at roughly knee height, front foot far enough forward that the shin stays close to vertical.',
          execution: 'Lower the rear knee toward the floor with the torso upright, then drive up through the front heel.',
          cue: 'Drive the floor down through the heel. Single-leg strength carries to high steps, rock-overs and long approaches.',
          breathing: 'Inhale down, exhale up.',
          mistakes: 'Front knee caving inward. Torso folding. Turning it into a high-rep burn set.',
        },
      },
      {
        id: 'home-sl-rdl',
        name: 'Single-Leg Romanian Deadlift',
        capacities: ['legs'],
        block: 'ACCESSORY', intensity: 'MODERATE',
        sets: 2, work: 10, unit: 'reps', restSec: 60,
        load: { kind: 'bodyweight', text: 'Bodyweight, or a pack held at the chest' },
        progression: 'Add load, then slow the lowering to 3 seconds.',
        protocolId: 'prehab',
        perSide: true,
        note: 'Posterior chain and single-leg balance. Cheap insurance for the knees and back.',
        form: {
          setup: 'Stand on one leg, slight knee bend, back flat.',
          execution: 'Hinge at the hip, sending the free leg back as the torso comes forward, until you feel a strong hamstring stretch. Return by driving the hips forward.',
          cue: 'Hinge, do not bend. Hips square to the floor throughout.',
          breathing: 'Inhale on the hinge, exhale on the return.',
          mistakes: 'Rounding the lower back. Letting the hip of the free leg rotate open.',
        },
      },
      {
        id: 'home-cuff-circuit',
        name: 'Cuff Circuit — External Rotation + Y-T-W',
        capacities: ['shoulder'],
        block: 'PREHAB', intensity: 'EASY',
        sets: 3, work: 12, unit: 'reps', restSec: 45,
        load: { kind: 'band', text: 'Light band — never to failure' },
        progression: 'Reps to 20, then a marginally heavier band. This stays light forever.',
        protocolId: 'prehab',
        note: '12 external rotations per side, then 12 each of Y, T and W with the band.',
        form: {
          setup: 'Band anchored at elbow height for rotations, held in both hands for Y-T-W.',
          execution: 'External rotations with the elbow pinned to the ribs. Then pull the band into a Y overhead, a T out to the sides and a W with elbows bent.',
          cue: 'Precision over load. This is scapular and cuff control, not a back workout.',
          breathing: 'Exhale on each pull.',
          mistakes: 'Shrugging. Using a heavy band and recruiting the lats.',
        },
      },
      {
        id: 'home-wrist-block',
        name: 'Wrist Conditioning',
        capacities: ['shoulder'],
        block: 'PREHAB', intensity: 'EASY',
        sets: 3, work: 12, unit: 'reps', restSec: 45,
        load: { kind: 'added-kg', text: 'Light: a 1-2kg weight, a full bottle, or a band' },
        progression:
          'Add reps to 15, then add a very small amount of weight. Slow throughout, '
          + '3 seconds on every lowering phase. This block gets heavier more slowly '
          + 'than anything else in the programme.',
        protocolId: 'prehab',
        perSide: true,
        note:
          'Four movements, 12 reps each: wrist extension palm-down, wrist flexion '
          + 'palm-up, radial and ulnar deviation, then slow pronation and supination '
          + 'holding the weight by one end. Never into pain.',
        form: {
          setup: 'Forearm supported on a thigh or table with the wrist just past the edge. Light weight or band in hand.',
          execution: 'Twelve controlled reps of each of the four movements, with a three-second lowering phase. Then repeat on the other side. Stop a movement immediately if it produces sharp or pinching pain rather than muscular effort.',
          cue: 'Climbing loads the wrist in one narrow band of positions under heavy crimp and mantle load, and trains nothing else. Steep crimping in particular is hard on the wrist. This block covers every direction the wrist can go, at a load it can actually adapt to.',
          breathing: 'Relaxed throughout. This should never feel like a lift.',
          mistakes: 'Going heavy. Rushing the lowering phase. Working into pain in the belief that it is strengthening something. Dropping the block as soon as the symptoms quieten down, which is the point at which it is working.',
        },
      },
      {
        id: 'home-hip-flow',
        name: 'Hip Mobility Flow',
        capacities: ['mobility'],
        block: 'MOBILITY', intensity: 'EASY',
        sets: 2, work: 150, unit: 'sec', restSec: 15,
        load: { kind: 'bodyweight', text: 'End range, loaded where possible' },
        progression: 'Push end range, then add gentle isometric contractions at end range to make the range usable.',
        protocolId: 'mobility',
        note: '90/90 both sides, frog, deep squat hold, couch stretch. Roughly 40s each.',
        form: {
          setup: 'Mat, floor space, something to hold onto for balance.',
          execution: '90/90 rotations both sides, frog stretch rocking, a deep squat hold, then a couch stretch per side. Two rounds.',
          cue: 'Combined abduction and external rotation is what makes high steps, drop knees and bridging available. Contract gently into end range so the range becomes usable rather than just passive.',
          breathing: 'Long exhales into each position.',
          mistakes: 'Bouncing. Holding your breath. Treating it as optional because nothing feels tight while warm.',
        },
      },
    ],
  },
];
