// =============================================================================
// data-morning.ts — MORN mode exercise data (wake-up routine)
// Equipment: Yoga mat, medium resistance band (no anchor), small pull edge
// Constraint: every circuit finishes inside 15 minutes at ANY level or energy.
//             That is enforced by rounds: 1 plus restCap on the circuit.
// =============================================================================

import type { Circuit } from './types';

export const DATA_MORNING: Circuit[] = [
  {
    id: 'morn-01', circuitNum: '01',
    title: 'ABS + OBLIQUES', subtitle: 'core - obliques - fingers',
    muscles: ['core', 'obliques'],
    illustration: 'core.svg',
    duration: 12, rounds: 1, restCap: 20,
    note: 'One round. Floor to standing. Under 15 minutes at every level.',
    exercises: [
      { id: 'morn-breathing', name: '90/90 Breathing Reset', muscles: ['core'],
        baseReps: 40, baseRest: 15, unit: 'sec', note: 'The only rule: get on the mat',
        variations: [{ minLevel: 1, name: '90/90 Breathing Reset' }, { minLevel: 4, name: '90/90 Breathing + Heel Press' }, { minLevel: 6, name: '90/90 Breathing + Band Pull-Apart' }],
        form: { setup: 'Lie on your back on the mat. Feet flat on a wall, a chair, or the floor with hips and knees both bent to 90 degrees. Arms resting at your sides, palms up. Press your lower back flat into the mat and keep it there.', execution: 'Inhale through the nose for 4 counts into the sides and back of your ribcage, not the belly. Exhale through pursed lips for 6-8 counts until you feel your ribs pull down and your abs switch on by themselves. That end-of-exhale position is the position every other exercise in this circuit is built on. For the heel press variation, push your heels into the wall or chair at about 20 percent effort throughout. For the band variation, hold the band overhead with light tension and pull it apart on each exhale.', cue: 'You are not stretching and you are not resting. The long exhale is what drops the ribcage and turns on the deep abdominal wall. If you feel your lower ribs flare up toward the ceiling, the exhale was too short.', breathing: 'This exercise IS the breathing. 4 seconds in through the nose, 6-8 seconds out through the mouth. Roughly 4 breath cycles in 40 seconds.', mistakes: 'Belly breathing instead of rib breathing. Lower back arching off the mat. Rushing the exhale. Skipping this because it feels too easy - it is the switch that makes the next 8 exercises work.' } },

      { id: 'morn-band-deadbug', name: 'Band Dead Bug', muscles: ['core'],
        baseReps: 16, baseRest: 15, unit: 'reps', note: 'Alternating - left plus right is 2 reps',
        variations: [{ minLevel: 1, name: 'Dead Bug' }, { minLevel: 4, name: 'Band Dead Bug' }, { minLevel: 6, name: 'Band Dead Bug 3s Hold' }],
        form: { setup: 'On your back, arms straight up over your chest, hips and knees at 90 degrees. For the band version, loop the band around the arches of both feet and hold one end in each hand, arms vertical, so the band runs from your hands down to your feet under light tension. Lower back pressed flat into the mat.', execution: 'Extend one leg out long and low while the opposite arm reaches back overhead. Go only as far as you can go without the lower back peeling off the mat. Return to the start under control and repeat on the other side. The band adds tension in both directions, so the return is loaded too.', cue: 'Imagine a strip of paper under your lower back that someone is trying to pull out. Your job for the whole set is to trap it. The moment it slips free, you went too far.', breathing: 'Exhale slowly as the limbs extend, inhale as they return. Never hold your breath - if you have to, reduce the range.', mistakes: 'Lower back arching as the leg lowers. Moving the arm and leg on the same side. Going fast - this is a control exercise, not a rep-chase. Letting the band yank the limbs back instead of resisting it.' } },

      { id: 'morn-hollow', name: 'Hollow Body Hold', muscles: ['core'],
        baseReps: 30, baseRest: 20, unit: 'sec',
        variations: [{ minLevel: 1, name: 'Hollow Body Hold - Tucked' }, { minLevel: 4, name: 'Hollow Body Hold' }, { minLevel: 6, name: 'Hollow Body Rocks' }],
        form: { setup: 'On your back. Press the lower back into the mat and squeeze the ribs down. Tucked version: knees pulled in toward the chest, hands reaching past the knees, shoulder blades just off the mat. Full version: arms overhead by the ears, legs straight and low.', execution: 'Hold the shape. The longer your arms and legs are, the harder the lever, so lengthen only as far as you can hold with the lower back glued down. For rocks, keep the exact same rigid shape and rock from shoulders to hips using the curve of your back, never bending in the middle.', cue: 'The shape is the exercise. This is the single best isometric for the rectus abdominis - the muscle whose segments are the visible pack - because it loads the whole sheet from ribcage to pubic bone at once, instead of just the top two segments the way a sit-up does.', breathing: 'Short, controlled breaths in and out through the mouth. Do not hold your breath. If your lower back lifts on the inhale, bend the knees more.', mistakes: 'Lower back arching - the whole exercise is lost. Chin jammed into the chest instead of a long neck. Arms drifting down to compensate. Holding to failure on day one and then dreading it tomorrow.' } },

      { id: 'morn-leg-lowers', name: 'Band Leg Lowers', muscles: ['core'],
        baseReps: 12, baseRest: 20, unit: 'reps',
        variations: [{ minLevel: 1, name: 'Bent-Knee Leg Lowers' }, { minLevel: 4, name: 'Band Leg Lowers' }, { minLevel: 6, name: 'Band Leg Lowers 5s Eccentric' }],
        form: { setup: 'On your back, legs up toward the ceiling. Hands flat under the glutes at first, then progress to arms by your sides. For the band version, loop the band over the arches of both feet and hold the ends at your chest, so the band resists the legs coming down. Lower back flat.', execution: 'Lower both legs slowly toward the floor, stopping the instant your lower back starts to arch. Pause there for a beat, then bring the legs back to vertical. Bent knees shorten the lever if the straight-leg version breaks your position. The 5-second eccentric variation takes a full 5 counts on the way down.', cue: 'This is the lower abdominal exercise. The bottom segments of the rectus abdominis - the two you are chasing for an 8-pack rather than a 6-pack - respond to posterior pelvic tilt under load, which is exactly what you are defending here.', breathing: 'Inhale as the legs lower, exhale hard as they come back up. The exhale helps you keep the ribs down.', mistakes: 'Letting the lower back arch to gain range - range you cannot control is worthless here. Yanking the legs back up with the hip flexors. Bouncing at the bottom. Neck straining - keep the head down on the mat.' } },

      { id: 'morn-side-plank', name: 'Side Plank Reach-Through', muscles: ['obliques', 'core'],
        baseReps: 12, baseRest: 20, unit: 'reps', note: 'Per side',
        variations: [{ minLevel: 1, name: 'Side Plank Reach-Through - Knees Down' }, { minLevel: 4, name: 'Side Plank Reach-Through' }, { minLevel: 6, name: 'Band Side Plank Reach-Through' }],
        form: { setup: 'Lie on your side. Elbow directly under the shoulder, forearm flat and pointing forward. Knees-down version: knees bent to 90 degrees, stacked, lifting from the knee. Full version: legs straight, feet stacked or staggered. Lift the hips so your body is one straight line. Top arm reaching up toward the ceiling.', execution: 'From the lifted position, rotate the torso and thread the top arm down and through the gap under your body, reaching as far behind you as you can. Then rotate back and reach the arm to the ceiling. That is one rep. Complete all reps on one side, then switch. The band version means holding the band under the bottom hand and pulling it as you reach up.', cue: 'The rotation is the point. Obliques run diagonally, so they only get fully loaded when the ribcage turns against a fixed pelvis - which is exactly what the reach-through is. Keep the hips high the entire time; if they drop, you have turned an oblique exercise into a shoulder exercise.', breathing: 'Exhale as you thread the arm through, inhale as you reach up. Steady rhythm.', mistakes: 'Hips sagging toward the floor between reps. Elbow out in front of the shoulder instead of under it. Rushing the thread-through with the arm alone instead of turning the whole ribcage. Doing an uneven number of reps per side.' } },

      { id: 'morn-pressout', name: 'Half-Kneeling Band Press-Out', muscles: ['obliques', 'core'],
        baseReps: 10, baseRest: 20, unit: 'reps', note: 'Per side',
        variations: [{ minLevel: 1, name: 'Half-Kneeling Band Press-Out' }, { minLevel: 4, name: 'Half-Kneeling Band Press-Out 3s Hold' }, { minLevel: 6, name: 'Tall-Kneeling Band Press-Out + Overhead' }],
        form: { setup: 'Half-kneeling on the mat: one knee down, the other foot forward and flat. Trap one end of the band under the down knee or under the front foot on that same side, and hold the other end in both hands at your sternum. The band now pulls diagonally down and across, which will try to twist and bend you toward it. Squeeze the glute of the down leg and stand tall through the spine.', execution: 'Press both hands straight out from your chest to full arm extension and hold for a beat, then bring them back to the sternum. The band gets harder as your hands travel away from your body. Do not let your ribcage turn or your torso tip toward the anchor. Complete the reps, then swap knees and band side.', cue: 'This is anti-rotation. You are not trying to twist - you are refusing to. Anti-rotation strength is what an oblique actually does on the wall when you are holding a body position against a barn-door, and it builds the deep waist tension that flexion work alone will never give you.', breathing: 'Exhale as you press out, inhale as you return. Do not brace by holding your breath - the tension lives in the abs, not the lungs.', mistakes: 'Letting the torso rotate or side-bend toward the band - the entire point is lost. Band too light to feel the pull. Front foot too close to the knee, which kills the base. Hips shifting instead of staying square and tall.' } },

      { id: 'morn-chop', name: 'Standing Band Chop', muscles: ['obliques', 'core'],
        baseReps: 12, baseRest: 20, unit: 'reps', note: 'Per side',
        variations: [{ minLevel: 1, name: 'Standing Band Chop' }, { minLevel: 4, name: 'Standing Band Chop 2s Hold' }, { minLevel: 6, name: 'Split-Stance Band Chop' }],
        form: { setup: 'Stand on one end of the band with the left foot, feet shoulder-width. Hold the other end in both hands, arms fairly straight, down by the left hip so the band is under tension. Soft knees, tall chest. This is the first standing exercise of the circuit - by design, you are getting up.', execution: 'Pull the band diagonally up and across your body, finishing with the hands high and outside the right shoulder, letting the ribcage rotate to follow. Control it back down to the left hip. All reps on one diagonal, then stand on the other end with the other foot and reverse. The split-stance version stands with one foot forward, which removes the hips from the equation and puts more of the work on the trunk.', cue: 'Drive the rotation from the ribs and the front-side obliques, not from the arms and not from the lower back. Your arms are a rope. Your trunk is the winch.', breathing: 'Exhale sharply on the way up and across, inhale on the controlled return.', mistakes: 'Chopping with the arms only while the torso stays still. Leaning back to get the hands higher. Letting the band snap you back down. Uneven rep counts left versus right - obliques are the easiest muscle in the body to build asymmetrically.' } },

      { id: 'morn-nohang', name: 'Pull Edge No-Hang', muscles: ['fingers', 'forearms', 'grip'],
        baseReps: 10, baseRest: 20, unit: 'sec', note: 'Per hand - 60 percent effort, NOT maximal',
        variations: [{ minLevel: 1, name: 'Pull Edge No-Hang - Open Hand' }, { minLevel: 4, name: 'Pull Edge No-Hang - Half-Crimp' }, { minLevel: 6, name: 'Pull Edge No-Hang - Half-Crimp Loaded' }],
        form: { setup: 'Loop the pull edge sling around one foot and sit or stand with that leg out in front of you. Take the edge in one hand. Open hand means all joints fairly extended, only the knuckle joint flexed. Half-crimp means the middle joints bent to about 90 degrees with the fingertip joints still slightly curved and the thumb OFF the index finger. Elbow slightly bent, shoulder packed down away from the ear.', execution: 'Build tension gradually over the first 2 seconds by pressing down through the foot - never snatch at it. Hold for 10 seconds at roughly 60 percent of what you could pull, then release over a second. Swap hands. Because you control the load with your leg rather than hanging bodyweight, you decide exactly how hard this is, which is what makes it safe first thing in the morning.', cue: 'This is the one exercise in the circuit where more is not better. Finger tendons and the surrounding tissue are cold, stiff and least hydrated right after waking. A submaximal daily pull keeps the tissue stimulated and the grip position sharp. A maximal one first thing is how climbers acquire a pulley injury. Save max hangs for HANG mode later in the day.', breathing: 'Normal, relaxed breathing throughout the 10 seconds. If you are holding your breath, you are pulling too hard - back off.', mistakes: 'Going near-maximal on cold tendons. Snatching the load on instead of easing into it. Any pain, clicking or pinching in a finger - stop the exercise entirely and skip it for the day. Thumb wrapped over the index finger, which turns half-crimp into full crimp. Doing this before the rest of the circuit instead of after, when you are still cold.' } },

      { id: 'morn-vacuum', name: 'Stomach Vacuum', muscles: ['core'],
        baseReps: 15, baseRest: 15, unit: 'sec', note: 'Best done before breakfast',
        variations: [{ minLevel: 1, name: 'Stomach Vacuum - Supine' }, { minLevel: 4, name: 'Stomach Vacuum - Quadruped' }, { minLevel: 6, name: 'Stomach Vacuum - Standing' }],
        form: { setup: 'Supine: on your back, knees bent, feet flat. Quadruped: on hands and knees with a flat back. Standing: feet shoulder-width, hands on the thighs. Each position removes a bit more help from gravity, which is why they unlock in that order.', execution: 'Exhale every last bit of air out of your lungs. With the lungs empty and without breathing in, pull your navel up and back toward your spine as hard as you can and hold. Aim for 15 seconds, then release and breathe normally. Repeat if the prescription calls for more than one hold.', cue: 'This trains the transverse abdominis - the deep corset layer that wraps the waist under the visible abs. It does nothing for the pack itself, but it is what pulls the whole midsection in and makes the obliques read as a defined line rather than a soft edge. Doing it fasted, right after waking, is genuinely the easiest time to get a full contraction.', breathing: 'The hold happens on empty lungs. Full exhale, then hold with no air. Come out of it the moment you need to breathe - do not turn this into a breath-hold contest.', mistakes: 'Sucking in without exhaling first - you cannot pull the wall in around a full ribcage. Holding so long you get lightheaded. Doing it on a full stomach. Confusing this with a crunch - nothing should shorten, only draw inward.' } },
    ],
  },

  {
    id: 'morn-02', circuitNum: '02',
    title: 'SLOW START', subtitle: 'mobility - core - grip',
    muscles: ['core', 'obliques', 'back'],
    illustration: 'morning.svg',
    duration: 11, rounds: 1, restCap: 20,
    note: 'For the bad mornings. Undoes the desk and the wall. Still counts.',
    exercises: [
      { id: 'morn-supine-twist', name: 'Supine Spinal Twist', muscles: ['obliques', 'back'],
        baseReps: 40, baseRest: 15, unit: 'sec', note: '20s per side',
        variations: [{ minLevel: 1, name: 'Supine Spinal Twist' }, { minLevel: 4, name: 'Supine Twist + Reach' }, { minLevel: 6, name: 'Supine Twist + Band Reach' }],
        form: { setup: 'On your back on the mat, arms out wide in a T. Draw both knees up toward your chest, then let them fall together to one side while keeping both shoulder blades on the floor.', execution: 'Rest there and breathe for 20 seconds, letting the knees sink lower on each exhale. Switch to the other side. The reach variation adds actively pressing the opposite arm along the floor away from the knees, which pulls the stretch further up the obliques and lats.', cue: 'The point is not to slam the knees to the floor. It is to keep the far shoulder pinned down while the pelvis rotates away from it - that is where the rotation actually happens.', breathing: 'Slow nasal inhales, long exhales. Around 4-5 breaths per side.', mistakes: 'Letting the top shoulder peel off the mat, which turns the stretch into a shrug. Forcing the knees down. Holding your breath. Skipping the second side because you got comfortable on the first.' } },

      { id: 'morn-catcow', name: 'Cat-Cow + Thread the Needle', muscles: ['back', 'core'],
        baseReps: 12, baseRest: 15, unit: 'reps', note: 'Alternate - 8 cat-cow then 4 threads',
        variations: [{ minLevel: 1, name: 'Cat-Cow + Thread the Needle' }, { minLevel: 4, name: 'Cat-Cow + Thread the Needle with Reach' }],
        form: { setup: 'On hands and knees. Hands under shoulders, knees under hips, spine long and neutral to start.', execution: 'Cat: press the floor away, round the whole spine up and tuck the tailbone. Cow: let the belly drop, lift the chest and tailbone. Move one vertebra at a time rather than hinging at one spot. After 8 of those, thread one arm under your body and across, letting the shoulder and the side of the head rest on the mat, then unwind and reach that arm to the ceiling. Alternate sides.', cue: 'This is the segment of the routine that gets your spine out of the shape it held all night and out of the shape climbing put it in. Move slowly enough that you can feel each vertebra arrive.', breathing: 'Inhale into cow, exhale into cat. On the thread, exhale as you reach through.', mistakes: 'Moving the whole spine as one rigid block. Cranking the neck. Hands drifting forward of the shoulders. Speeding up - this is the wake-up, not the workout.' } },

      { id: 'morn-hip-9090', name: '90/90 Hip Switch', muscles: ['legs', 'glutes'],
        baseReps: 12, baseRest: 15, unit: 'reps', note: 'Left plus right is 2 reps',
        variations: [{ minLevel: 1, name: '90/90 Hip Switch' }, { minLevel: 4, name: '90/90 Hip Switch + Lift' }],
        form: { setup: 'Sit on the mat with both knees bent at 90 degrees, one leg in front of you and one out to the side, both shins on the floor. Sit tall with the hands lightly behind or in front for balance.', execution: 'Without using your hands, lift both knees and rotate them through the middle to the mirror-image position on the other side. Move slowly and under control. The lift variation pauses with the knees off the floor mid-rotation.', cue: 'Climbers lose internal hip rotation faster than almost any other range, and losing it is what stops you getting your hip into the wall. Three minutes a day of this is worth more than an hour of stretching once a month.', breathing: 'Exhale through the rotation, inhale in the settled position.', mistakes: 'Pushing off the hands. Rounding the lower back to compensate for tight hips - sit on a folded edge of the mat if you cannot sit upright. Rushing through the middle instead of controlling it.' } },

      { id: 'morn-pullapart', name: 'Band Pull-Apart + Overhead Pass', muscles: ['shoulders', 'back'],
        baseReps: 15, baseRest: 15, unit: 'reps',
        variations: [{ minLevel: 1, name: 'Band Pull-Apart' }, { minLevel: 4, name: 'Band Pull-Apart + Overhead Pass' }, { minLevel: 6, name: 'Band Pull-Apart + Full Dislocate' }],
        form: { setup: 'Stand tall. Hold the band in both hands in front of you at shoulder height, arms straight, hands wide enough that there is already light tension. Ribs down, glutes lightly on.', execution: 'Pull the band apart until your hands are out wide and the band touches your chest, squeezing the shoulder blades together. Return under control. On the overhead pass, after the pull-apart continue the hands up and back over your head as far as your shoulders allow, then reverse the path. Widen your grip if it feels pinchy.', cue: 'Climbing and sitting both pull you into the same rounded, internally rotated shoulder position. This is the direct antidote, and it takes 40 seconds. Think about the shoulder blades doing the work, not the hands.', breathing: 'Exhale on the pull-apart, inhale on the return.', mistakes: 'Arching the lower back to fake overhead range. Shrugging the shoulders up to the ears. Grip too narrow for your current shoulder mobility. Bending the elbows to cheat the pull.' } },

      { id: 'morn-birddog', name: 'Bird Dog', muscles: ['core', 'back'],
        baseReps: 12, baseRest: 20, unit: 'reps', note: 'Alternating - slow',
        variations: [{ minLevel: 1, name: 'Bird Dog' }, { minLevel: 4, name: 'Bird Dog 3s Hold' }, { minLevel: 6, name: 'Bird Dog + Elbow-to-Knee' }],
        form: { setup: 'Hands and knees, spine neutral. Imagine balancing a glass of water on your lower back - it must not spill for the whole set.', execution: 'Extend one arm forward and the opposite leg back until both are level with the torso. Hold briefly, then return without touching down and switch sides. The advanced version draws the elbow and knee together underneath you before extending again.', cue: 'The moving limbs are a distraction. The exercise is your trunk refusing to rotate or tip while they move - the same anti-rotation demand as the press-out, just on the floor while you are still half asleep.', breathing: 'Exhale as you extend, inhale as you return. Stay smooth.', mistakes: 'Hips rotating open as the leg lifts. Kicking the leg above hip height and arching the back. Reaching too fast. Head lifting up instead of staying in line with the spine.' } },

      { id: 'morn-glute-bridge-march', name: 'Glute Bridge March', muscles: ['glutes', 'core'],
        baseReps: 16, baseRest: 20, unit: 'reps', note: 'Left plus right is 2 reps',
        variations: [{ minLevel: 1, name: 'Glute Bridge Hold' }, { minLevel: 4, name: 'Glute Bridge March' }, { minLevel: 6, name: 'Band Glute Bridge March' }],
        form: { setup: 'On your back, feet hip-width and flat, heels about 30cm from your glutes, arms at your sides. For the band version, loop the band around both thighs just above the knees.', execution: 'Drive through the heels and lift the hips until there is a straight line from knees to shoulders. From that position, lift one foot a few centimetres off the floor without letting the hips drop or tilt, place it back, then the other. Keep the hips high for the whole set.', cue: 'A night of sleep and a day of sitting both switch the glutes off. Marching means the pelvis has to stay level on one leg, which is the same demand as high-stepping on the wall.', breathing: 'Steady breathing at the top. Exhale on each foot lift.', mistakes: 'Hips dropping as soon as a foot lifts. Rushing the march. Pushing through the toes instead of the heels. Hyperextending the lower back at the top instead of finishing with the glutes.' } },

      { id: 'morn-side-plank-hold', name: 'Side Plank Hold', muscles: ['obliques', 'core'],
        baseReps: 25, baseRest: 20, unit: 'sec', note: 'Per side',
        variations: [{ minLevel: 1, name: 'Side Plank Hold - Knees Down' }, { minLevel: 4, name: 'Side Plank Hold' }, { minLevel: 6, name: 'Side Plank Hold + Top Leg Raise' }],
        form: { setup: 'On your side, elbow under the shoulder, forearm forward. Knees bent and stacked for the easier version, legs straight and feet stacked or staggered for the full one. Lift the hips into a straight line, top hand on the hip or reaching to the ceiling.', execution: 'Hold. Full time on one side, then the other. The advanced version lifts and holds the top leg, which turns it into a hip abduction exercise on top of the oblique hold.', cue: 'Push the floor away with the forearm and lift the bottom ribs toward the ceiling. If the bottom shoulder sinks, you are hanging on the joint instead of holding with the obliques.', breathing: 'Slow and steady. If you cannot breathe evenly, drop to the knees-down version.', mistakes: 'Hips sagging. Body rolling forward or back off the true side position. Bottom shoulder collapsing. Doing 40 seconds on the strong side and 15 on the weak one.' } },

      { id: 'morn-nohang-easy', name: 'Pull Edge No-Hang - Open Hand', muscles: ['fingers', 'forearms'],
        baseReps: 10, baseRest: 20, unit: 'sec', note: 'Per hand - light, this is circulation not strength',
        variations: [{ minLevel: 1, name: 'Pull Edge No-Hang - Open Hand' }, { minLevel: 4, name: 'Pull Edge No-Hang - Open Hand + Roll' }],
        form: { setup: 'Loop the pull edge sling around one foot, leg extended in front. Take the edge in one hand in a relaxed open-hand position - joints mostly extended, no crimping at all. Elbow soft, shoulder packed.', execution: 'Ease into a light pull over 2 seconds, hold for 10 at maybe 40-50 percent effort, release. Swap hands. On the roll variation, slowly curl the fingers from open hand toward half-crimp and back once during the hold, moving through the range under gentle load.', cue: 'On a recovery morning the fingers want blood flow and a reminder of the position, not a stimulus. If yesterday was a hard climbing day, this is the version to do - and if the fingers feel stiff or achy, skip it and lose one XP rather than losing six weeks.', breathing: 'Completely relaxed. If you are bracing, it is too heavy.', mistakes: 'Treating this as a strength set. Any crimping. Pulling through pain or through morning stiffness that has not eased. Doing it before the mobility work rather than after.' } },

      { id: 'morn-deadbug-slow', name: 'Slow Dead Bug', muscles: ['core'],
        baseReps: 14, baseRest: 15, unit: 'reps', note: 'Alternating - 4s per rep',
        variations: [{ minLevel: 1, name: 'Slow Dead Bug' }, { minLevel: 4, name: 'Slow Dead Bug 4s Tempo' }, { minLevel: 6, name: 'Band Slow Dead Bug' }],
        form: { setup: 'On your back, arms up over the chest, hips and knees at 90 degrees, lower back pressed flat into the mat. Same shape as the banded version in circuit 01, no band needed.', execution: 'Extend one leg and the opposite arm slowly - about 2 seconds out and 2 seconds back - going only as far as the flat lower back allows. Alternate. This is the last exercise deliberately: it finishes you in the braced position rather than a stretched one, so you stand up switched on.', cue: 'Slower is harder here, not easier. The tempo is the load.', breathing: 'Long exhale on the extension, inhale on the return. Match the breath to the 4-second tempo and the set paces itself.', mistakes: 'Speeding up as it gets uncomfortable. Lower back lifting. Same-side arm and leg. Finishing the set and immediately slumping - stand up tall and keep the rib position for a few seconds.' } },
    ],
  },
];
