// =============================================================================
// data-cave.ts — CAVE mode: full gym sessions
// Equipment: hangboard, rings, TRX, campus board, kettlebells, dumbbells and
//            plates, pull-up bars, weighted pull-up harness, a pulley under the
//            hangboard, bands + anchors, bouldering wall with slab and steep.
//
// Six sessions:
//   01 MAX      — fingers, heavy pulling and the one-arm path, all fresh.
//   02 POWER    — limit bouldering and contact strength.
//   03 CAPACITY — repeaters, strength endurance, antagonists, legs.
//   04 ASSESS   — the test battery. Every 6-8 weeks, on a rest day. Results
//                 are saved as benchmarks and open the safety gates.
//   05 ADD-ON   — after bouldering: heavy pull, one-arm path, antagonists, core.
//   06 FEET     — after bouldering: footwork, balance, slab, feet-on tension.
//
// Order inside every session is fixed by neurological cost: the fingers and the
// nervous system get the session while they are fresh, and the conditioning
// work goes last where fatigue costs nothing.
// =============================================================================

import type { Circuit } from './types';
import { oneArmPath, assistedOneArm, oneArmNegative, oneArmShrug } from './data-oap';

const WARMUP_PULSE = {
  id: 'cave-warmup-pulse',
  name: 'Pulse Raiser + Shoulder Prep',
  capacities: ['shoulder' as const],
  block: 'WARMUP' as const, intensity: 'EASY' as const,
  sets: 1, work: 300, unit: 'sec' as const, restSec: 30,
  load: { kind: 'bodyweight' as const, text: 'No load' },
  fixed: true,
  progression: 'Never progressed. Preparation, not training.',
  protocolId: 'warmup',
  note: 'Pulse raiser, band external rotations, scapular pull-ups, easy traversing.',
  form: {
    setup: 'Band anchored at elbow height. Space to move.',
    execution: 'Three minutes raising the pulse, then 15 band external rotations per side, 10 scapular pull-ups, 5 minutes of easy traversing or jugs.',
    cue: 'Warm and switched on, not tired. You should finish wanting to climb.',
    breathing: 'Nasal, unhurried.',
    mistakes: 'Treating it as optional because you feel fine. Turning it into a session.',
  },
};

const WARMUP_FINGERS = {
  id: 'cave-warmup-fingers',
  name: 'Progressive Finger Loading',
  capacities: ['crimp' as const, 'openhand' as const],
  block: 'WARMUP' as const, intensity: 'EASY' as const,
  sets: 3, work: 10, unit: 'sec' as const, restSec: 60,
  load: { kind: 'percent-max' as const, value: 50, text: 'Jug > 30mm > 20mm, 40-60%' },
  fixed: true,
  progression: 'Never progressed.',
  protocolId: 'warmup',
  form: {
    setup: 'Biggest hold first, stepping down in size. Feet on the floor to control load.',
    execution: 'Ten seconds on, sixty off, three times.',
    cue: 'The last warm-up hang is the readiness check. Tender or sharp means the session gets downgraded, today, without negotiation.',
    breathing: 'Normal throughout.',
    mistakes: 'Skipping straight to the working load.',
  },
};

export const DATA_CAVE: Circuit[] = [
  {
    id: 'cave-01', circuitNum: '01',
    title: 'MAX', subtitle: 'fingers - heavy pull',
    focus: 'Raise the ceiling: peak finger force and maximal pulling, both fresh.',
    capacities: ['crimp', 'pull', 'tension'],
    illustration: 'maxhangs.svg',
    duration: 65,
    recoveryHours: 48,
    note: 'Every set here is meant to be hard and well rested. If you are rushing, cut an exercise, not the rest.',
    exercises: [
      WARMUP_PULSE,
      { ...WARMUP_FINGERS, sets: 4 },
      {
        id: 'cave-max-hang',
        name: 'Max Hang — Half-Crimp 20mm',
        capacities: ['crimp'],
        block: 'PRIMARY', intensity: 'MAX',
        sets: 4, work: 10, unit: 'sec', restSec: 180,
        load: { kind: 'percent-max', value: 88, text: '20mm, 85-90% of tested 10s max' },
        progression: 'All four sets clean at 10s, then add 1-2kg next session.',
        protocolId: 'max-hang',
        note: 'Twenty millimetres, always. Smaller edges concentrate load over a shorter contact area and are not a testing tool for fingers that are complaining. Any sharpness, tenderness or joint ache: stop the session and do DENSITY instead.',
        variations: [
          { minLevel: 1, name: 'Half-Crimp 20mm — Build', load: 'Feet assisted. 10s at RPE 7: comfortably hard, never maximal. Live here 6-8 weeks.' },
          { minLevel: 3, name: 'Half-Crimp 20mm — Bodyweight', load: 'Bodyweight or light assist, 10s at RPE 8' },
          { minLevel: 4, name: 'Half-Crimp 20mm — Weighted', load: '20mm + weight, 85-90% of tested 10s max' },
          { minLevel: 6, name: 'Half-Crimp 20mm — Heavy', load: '20mm at 140%+ bodyweight (+25kg at 62kg)' },
          { minLevel: 7, name: 'Half-Crimp 15mm', load: '15mm. Only past 150% on 20mm, and only after a quiet season.' },
        ],
        form: {
          setup: 'Second knuckles at roughly 90 degrees, first knuckles extended, thumb off. Elbows slightly bent, shoulders down and back, ribs down, glutes engaged.',
          execution: 'Ten seconds, then step off deliberately. Stop the set when the position degrades, not when the timer says so.',
          cue: 'Pull the edge toward you. The body is a plank hanging from the fingers, not a sack.',
          breathing: 'Breathe through it.',
          mistakes: 'Drifting into full crimp or open drag under fatigue. Locked elbows. Adding load before the current load is clean.',
        },
      },
      {
        id: 'cave-weighted-pullup',
        name: 'Weighted Pull-Ups',
        capacities: ['pull'],
        block: 'PRIMARY', intensity: 'MAX',
        sets: 4, work: 4, unit: 'reps', restSec: 180,
        load: { kind: 'added-kg', text: 'RPE 8-9 — a load leaving 1-2 reps in reserve' },
        progression:
          'When all four sets hit 4 clean reps, add 2kg. This is the single highest-value '
          + 'strength lift in the programme while your weighted pull-up sits under 165% bodyweight.',
        protocolId: 'max-strength',
        variations: [
          { minLevel: 1, name: 'Pull-Ups — Bodyweight', load: 'Bodyweight, 4-5 hard reps' },
          { minLevel: 2, name: 'Pull-Ups — Slow Eccentric', load: 'Bodyweight, 4s lower' },
          { minLevel: 4, name: 'Weighted Pull-Ups', load: 'Belt or pack, RPE 8-9' },
          { minLevel: 6, name: 'Weighted Pull-Ups — Heavy', load: '+20% bodyweight or more' },
        ],
        form: {
          setup: 'Full dead hang, pronated grip just outside shoulder width. Weight on a belt hanging between the legs, or a loaded pack.',
          execution: 'Pull elbows down and back until the chin clears the bar, chest leading. Lower under control to a complete dead hang every rep.',
          cue: 'Elbows to your back pockets. Start each rep from a genuine dead hang or you are training half a movement.',
          breathing: 'Exhale on the pull, inhale on the descent.',
          mistakes: 'Kipping. Stopping short of a dead hang. Choosing a load that turns four reps into a grinding set of eight.',
        },
      },
      // One-arm pull-up path, fresh. Gated rungs appear as the tested weighted
      // pull-up clears them; see data-oap.ts.
      oneArmShrug('cave01-oap-shrug'),
      assistedOneArm('cave01-oap-assisted', 'cave01-oap-path', 'pulley'),
      oneArmNegative('cave01-oap-negative'),
      {
        id: 'cave-lockoff',
        name: 'Lock-Off Ladder',
        capacities: ['pull'],
        block: 'SECONDARY', intensity: 'HARD',
        sets: 3, work: 15, unit: 'sec', restSec: 120,
        load: { kind: 'bodyweight', text: 'Bodyweight, assisted or weighted as needed' },
        progression: 'Add 2s per position, then remove assistance, then add weight.',
        protocolId: 'lock-off',
        perSide: true,
        note: '5s at 120 degrees, 5s at 90, 5s at 60. One continuous descent per set.',
        form: {
          setup: 'Bar or rings. Pull to the top, then lower into the first hold position.',
          execution: 'Hold five seconds at each of three elbow angles on the way down. Use the free hand lightly on the wrist for one-arm versions.',
          cue: 'Climbing pulling is mostly isometric and position-specific. Train the angle where you actually fail: usually 90 degrees.',
          breathing: 'Keep breathing through the holds.',
          mistakes: 'Sinking through positions instead of holding them. Shrugging into the ears.',
        },
      },
      {
        id: 'cave-front-lever',
        name: 'Front Lever Progression',
        capacities: ['tension'],
        block: 'SECONDARY', intensity: 'HARD',
        sets: 4, work: 10, unit: 'sec', restSec: 90,
        load: { kind: 'bodyweight', text: 'Hardest progression you can hold with a flat lower back' },
        progression: 'Hold 4 x 12s clean, then move to the next progression and reset to 8s.',
        protocolId: 'tension-iso',
        variations: [
          { minLevel: 1, name: 'Tuck Front Lever' },
          { minLevel: 3, name: 'Advanced Tuck Front Lever' },
          { minLevel: 5, name: 'One-Leg Front Lever' },
          { minLevel: 6, name: 'Straddle Front Lever' },
          { minLevel: 7, name: 'Full Front Lever' },
        ],
        form: {
          setup: 'Hang from a bar or rings, arms straight, shoulders depressed and protracted slightly.',
          execution: 'Pull the body to horizontal in your chosen progression and hold. Lower back stays flat against an imaginary wall.',
          cue: 'Push the bar away with straight arms rather than pulling. Ribs down, glutes squeezed, pelvis tucked.',
          breathing: 'Short controlled breaths. Do not hold your breath for the whole set.',
          mistakes: 'Arching the lower back, which makes the hold easier and trains nothing. Bent arms. Chasing the next progression before the current one is clean.',
        },
      },
      {
        id: 'cave-band-er',
        name: 'Band External Rotation',
        capacities: ['shoulder'],
        block: 'PREHAB', intensity: 'EASY',
        sets: 2, work: 15, unit: 'reps', restSec: 45,
        load: { kind: 'band', text: 'Light band — never to failure' },
        progression: 'Add reps to 20, then a slightly heavier band. Never heavy.',
        protocolId: 'prehab',
        perSide: true,
        form: {
          setup: 'Band anchored at elbow height. Elbow tucked to the ribs at 90 degrees, towel under the armpit if that helps hold position.',
          execution: 'Rotate the forearm outward, keeping the elbow pinned. Slow return.',
          cue: 'Climbing loads the internal rotators relentlessly and the external rotators barely at all. This is the balance payment.',
          breathing: 'Exhale on the rotation out.',
          mistakes: 'Elbow drifting from the ribs. Using body English. Going heavy — this is maintenance, not a lift.',
        },
      },
    ],
    substitutes: [oneArmPath('cave01-oap-path')],
  },
  {
    id: 'cave-02', circuitNum: '02',
    title: 'POWER', subtitle: 'limit boulder - contact',
    focus: 'Recruit harder: maximal moves, contact strength, explosive pulling.',
    capacities: ['contact', 'crimp', 'pull', 'tension'],
    illustration: 'kettlebell.svg',
    duration: 58,
    recoveryHours: 48,
    note: 'Quality decides the length of this session. When attempts stop feeling explosive, it is over.',
    exercises: [
      WARMUP_PULSE,
      WARMUP_FINGERS,
      {
        id: 'cave-limit-boulder',
        name: 'Limit Bouldering',
        capacities: ['contact', 'crimp', 'tension', 'pull'],
        block: 'PRIMARY', intensity: 'MAX',
        sets: 6, work: 1, unit: 'reps', restSec: 180,
        load: { kind: 'rpe', value: 10, text: 'Problems you can do in 1-4 tries on a good day' },
        progression: 'Harder problems, not more attempts. Six maximal attempts beats twelve tired ones.',
        protocolId: 'limit-boulder',
        note: 'Four to six move problems at your limit. One attempt per set.',
        form: {
          setup: 'Pick two or three problems that are genuinely hard for you, ideally on steep ground with small holds.',
          execution: 'One full attempt per set, then three minutes of real rest. Sit down, breathe, do not fiddle with your phone under the board.',
          cue: 'This is the most transferable power stimulus you have: fingers, tension and movement loaded together in the pattern the sport actually uses.',
          breathing: 'Full recovery breathing between attempts. Commit and breathe out on the hard move.',
          mistakes: 'Cutting rest to three attempts in five minutes. Continuing once quality drops. Choosing problems that suit you rather than ones that expose you.',
        },
      },
      {
        id: 'cave-campus',
        name: 'Campus Ladders',
        capacities: ['contact', 'pull'],
        block: 'PRIMARY', intensity: 'MAX',
        sets: 4, work: 1, unit: 'reps', restSec: 180,
        load: { kind: 'bodyweight', text: '1-3-5 ladder, large rungs' },
        progression: 'Add a rung span (1-4-7) before adding sets. Never more than 5 sets.',
        protocolId: 'campus',
        gate: {
          benchmarkId: 'fs-2arm-20mm',
          minValue: 130,
          reason:
            'Campus boarding is the highest injury-risk tool in the gym and loads fingers, '
            + 'elbows and shoulders explosively. It stays locked until your 20mm two-arm hang '
            + 'is at least 130% bodyweight and you have had four clear weeks with no finger or '
            + 'elbow pain. Recruitment pulls give most of the benefit at a fraction of the risk.',
          substituteId: 'cave-recruitment-pulls',
        },
        form: {
          setup: 'Large rungs. Fully warm, after the limit boulders, never at the end of a session.',
          execution: 'Match on rung 1, move up to 3, then 5, controlled. One ladder per set. Stop the exercise the moment a catch feels sloppy.',
          cue: 'Stop while it still feels good. Every campus injury happens on the set someone should not have done.',
          breathing: 'Sharp exhale on each move.',
          mistakes: 'Campusing tired. Campusing on small rungs. Doing it because it looks impressive rather than because a test says you need it.',
        },
      },
      {
        id: 'cave-explosive-pull',
        name: 'Explosive Pull-Ups',
        capacities: ['pull', 'contact'],
        block: 'SECONDARY', intensity: 'HARD',
        sets: 3, work: 3, unit: 'reps', restSec: 150,
        load: { kind: 'bodyweight', text: 'Bodyweight, maximal speed' },
        progression: 'Chest to bar, then hands leaving the bar, then a small added load.',
        protocolId: 'max-strength',
        form: {
          setup: 'Dead hang, shoulders engaged before the pull starts.',
          execution: 'Pull as fast as you physically can, aiming to bring the chest to the bar. Lower under control, reset fully between reps.',
          cue: 'Three reps means three maximal-speed reps. The moment speed drops the set is finished.',
          breathing: 'Sharp exhale on each pull.',
          mistakes: 'Grinding out slow reps. Using a swing to generate the speed.',
        },
      },
      {
        id: 'cave-toehook',
        name: 'Ring Toe-Hook Hold',
        capacities: ['tension'],
        block: 'SECONDARY', intensity: 'HARD',
        sets: 3, work: 8, unit: 'reps', restSec: 90,
        load: { kind: 'bodyweight', text: 'Bodyweight' },
        progression: 'Longer holds, then a straighter body, then one arm on the rings.',
        protocolId: 'tension-iso',
        note: 'Hang from rings, hook both heels over a bar or ring strap, hold body horizontal.',
        form: {
          setup: 'Rings at head height, feet hooked over a low bar or the straps.',
          execution: 'Pull the body into a horizontal line and hold, or move slowly between positions for reps.',
          cue: 'This is the tension climbing actually asks for: pulling with the feet while the hands hold. Steep rock is won here.',
          breathing: 'Continuous, controlled.',
          mistakes: 'Letting the hips drop. Relying on the arms and forgetting the feet are meant to be pulling.',
        },
      },
      {
        id: 'cave-trx-ytw',
        name: 'TRX Y-T-W',
        capacities: ['shoulder'],
        block: 'PREHAB', intensity: 'EASY',
        sets: 2, work: 10, unit: 'reps', restSec: 45,
        load: { kind: 'bodyweight', text: 'Angle sets the load — stay light' },
        progression: 'Walk the feet forward to steepen the angle. Never to failure.',
        protocolId: 'prehab',
        note: 'Ten reps in each of the three positions.',
        form: {
          setup: 'TRX or rings, lean back with arms straight, body rigid, feet forward enough to feel resistance.',
          execution: 'Pull into a Y overhead, then a T out to the sides, then a W with elbows bent. Ten each.',
          cue: 'Scapular control, not a back workout. Slow and precise beats heavy.',
          breathing: 'Exhale on the pull.',
          mistakes: 'Shrugging. Steepening the angle until it becomes a row.',
        },
      },
    ],
    substitutes: [
      {
        id: 'cave-recruitment-pulls',
        name: 'Recruitment Pulls',
        capacities: ['contact', 'crimp'],
        block: 'PRIMARY', intensity: 'MAX',
        sets: 4, work: 5, unit: 'sec', restSec: 150,
        load: { kind: 'rpe', value: 10, text: 'Maximal intent against an immovable edge' },
        progression: 'Measured peak force on a gauge, or a heavier block. Intent is the variable, not duration.',
        protocolId: 'recruitment-pull',
        note: 'Pull as hard as possible for 5 seconds. Reaching peak force fast is the point.',
        form: {
          setup: 'A block or edge fixed so it cannot move, or a hangboard edge with feet planted and a weight belt anchored down.',
          execution: 'Build to maximum force as fast as you can and hold five seconds. Full effort from the first half-second.',
          cue: 'Contact strength is how fast you reach force, not how much you eventually reach. Intent is the training variable.',
          breathing: 'Brace and exhale hard through the pull.',
          mistakes: 'Easing into the pull. Doing these fatigued, where maximal intent is not available.',
        },
      },
    ],
  },
  {
    id: 'cave-03', circuitNum: '03',
    title: 'CAPACITY', subtitle: 'repeaters - endurance - armour',
    focus: 'Build the engine: sustain force for longer, and pay the antagonist and leg bills.',
    capacities: ['forearm', 'pull', 'press', 'legs', 'shoulder'],
    illustration: 'hangboard.svg',
    duration: 58,
    recoveryHours: 24,
    note: 'The lowest-intensity session of the three. It should leave you tired but not wrecked.',
    exercises: [
      WARMUP_PULSE,
      WARMUP_FINGERS,
      {
        id: 'cave-repeaters',
        name: 'Repeaters 7:3',
        capacities: ['forearm', 'crimp'],
        block: 'PRIMARY', intensity: 'HARD',
        sets: 6, work: 60, unit: 'sec', restSec: 150,
        load: { kind: 'percent-max', value: 60, text: '55-65% of max hang load' },
        fixed: true,
        progression: 'Six sets is the dose. When all six complete without early drops, add 1kg.',
        protocolId: 'repeaters',
        note: '7s on, 3s off, six times = one set.',
        form: {
          setup: 'Half-crimp on 20mm, timer running before you start.',
          execution: 'Seven on, three off, six times. Shake out in the three-second gaps.',
          cue: 'The last two reps of each set should be a fight. If set six matches set one, the load is too light.',
          breathing: 'Rhythmic. Exhale on the releases.',
          mistakes: 'Loading it like a max hang. Staying on the edge through the rest windows.',
        },
      },
      {
        id: 'cave-pullup-se',
        name: 'Pull-Up Strength Endurance',
        capacities: ['pull'],
        block: 'SECONDARY', intensity: 'MODERATE',
        sets: 4, work: 8, unit: 'reps', restSec: 120,
        load: { kind: 'rpe', value: 7, text: 'RPE 7-8 — two or three reps left at the end' },
        progression: 'Add a rep per set to 12, then add load and drop back to 8.',
        protocolId: 'strength-endurance',
        form: {
          setup: 'Bar or rings, full dead hang.',
          execution: 'Eight controlled reps, full range, no kipping. Stop two or three short of failure.',
          cue: 'This is the bridge between a heavy single and a 30-move route. It is deliberately not a max effort.',
          breathing: 'Exhale on each pull.',
          mistakes: 'Taking every set to failure and wrecking the rest of the session.',
        },
      },
      {
        id: 'cave-kb-press',
        name: 'KB Overhead Press',
        capacities: ['press', 'shoulder'],
        block: 'SECONDARY', intensity: 'MODERATE',
        sets: 3, work: 8, unit: 'reps', restSec: 90,
        load: { kind: 'added-kg', value: 12, text: 'KB 12kg, single arm' },
        progression: 'Add reps to 12, then move to a half-kneeling or single-leg stance for a harder position.',
        protocolId: 'max-strength',
        perSide: true,
        note: 'Overhead pressing is the antagonist that matters most for a climbing shoulder.',
        form: {
          setup: 'Kettlebell racked at the shoulder, elbow tucked, wrist straight, ribs down.',
          execution: 'Press overhead until the biceps is beside the ear, shoulder actively pushing up at the top. Lower under control.',
          cue: 'Finish every rep with the shoulder fully overhead. Climbers lose that range, and losing it is how shoulders start hurting.',
          breathing: 'Exhale on the press.',
          mistakes: 'Leaning back to press. Stopping short of full overhead. Flared ribs.',
        },
      },
      {
        id: 'cave-split-squat',
        name: 'Bulgarian Split Squat',
        capacities: ['legs'],
        block: 'ACCESSORY', intensity: 'MODERATE',
        sets: 3, work: 8, unit: 'reps', restSec: 90,
        load: { kind: 'added-kg', value: 12, text: 'Bodyweight, then KB goblet' },
        progression: 'Bodyweight to 12 reps, then hold the kettlebell, then two.',
        protocolId: 'max-strength',
        perSide: true,
        note: 'Single-leg strength carries to high steps, rock-overs and long approach days.',
        form: {
          setup: 'Rear foot on a bench at roughly knee height. Front foot far enough forward that the shin stays near vertical.',
          execution: 'Lower the rear knee toward the floor, torso upright, then drive up through the front heel.',
          cue: 'Drive the floor away through the heel. Balance is part of the exercise.',
          breathing: 'Inhale down, exhale up.',
          mistakes: 'Front knee collapsing inward. Torso folding forward. Bouncing the back knee off the floor.',
        },
      },
      {
        id: 'cave-wrist-armour',
        name: 'Wrist Extensor + Pronator',
        capacities: ['shoulder'],
        block: 'PREHAB', intensity: 'EASY',
        sets: 2, work: 15, unit: 'reps', restSec: 45,
        load: { kind: 'added-kg', text: 'Light dumbbell or band' },
        progression: 'Add reps to 20, then a marginally heavier weight. Slow tempo throughout.',
        protocolId: 'prehab',
        perSide: true,
        note: 'Wrist extension then pronation. The standard prevention for medial elbow pain in climbers.',
        form: {
          setup: 'Forearm supported on a bench or thigh, wrist over the edge, light dumbbell in hand.',
          execution: 'Fifteen wrist extensions palm-down, then fifteen slow pronations holding the dumbbell by one end. Three seconds on the lowering phase.',
          cue: 'Climbing trains the finger and wrist flexors constantly and the extensors almost never. Golfer elbow lives in that gap.',
          breathing: 'Relaxed.',
          mistakes: 'Going heavy and fast. Skipping it because nothing hurts yet, which is exactly when it works.',
        },
      },
    ],
  },
  {
    id: 'cave-04', circuitNum: '04',
    title: 'ASSESS', subtitle: 'test - not train',
    focus: 'Find the limiter. Numbers now, opinions later.',
    capacities: ['crimp', 'openhand', 'pull', 'tension', 'mobility'],
    illustration: 'dumbbell.svg',
    duration: 45,
    recoveryHours: 48,
    note:
      'Run this every 6-8 weeks on a rest day, fully warm and fresh. Enter each result on '
      + 'the stepper before the last DONE: it is saved as a benchmark, and benchmarks are '
      + 'what open the campus board and the one-arm gates.',
    exercises: [
      WARMUP_PULSE,
      { ...WARMUP_FINGERS, sets: 4 },
      {
        id: 'test-max-hang',
        name: 'TEST — Max Hang 20mm Half-Crimp',
        capacities: ['crimp'],
        block: 'TEST', intensity: 'MAX',
        sets: 4, work: 10, unit: 'sec', restSec: 180,
        load: { kind: 'percent-max', text: 'Build up until 10s is the most you can hold' },
        progression: 'Record (bodyweight + added) / bodyweight x 100. At 62kg: 128% = +17kg, 134% = +21kg, 140% = +25kg.',
        protocolId: 'assessment',
        note: 'Work up in 3-5kg jumps. Stop at the first failed 10s and record the last success.',
        records: {
          benchmarkId: 'fs-2arm-20mm',
          axis: { unit: 'kg', step: 1, min: 0, max: 80, prefix: '+', label: 'BEST 10S, ADDED' },
          convert: 'added-kg-to-pct-bw',
        },
        form: {
          setup: 'Identical setup every test: same edge, same grip, same shoulder position, same time of day if possible.',
          execution: 'Ten seconds. Successive attempts with three minutes between. Record the heaviest clean 10s.',
          cue: 'A test only works if it is repeatable. Change nothing between tests except your training.',
          breathing: 'Normal.',
          mistakes: 'Testing tired. Changing edge size between tests and comparing the numbers anyway.',
        },
      },
      {
        id: 'test-weighted-pullup',
        name: 'TEST — Weighted Pull-Up 5RM',
        capacities: ['pull'],
        block: 'TEST', intensity: 'MAX',
        sets: 3, work: 5, unit: 'reps', restSec: 180,
        load: { kind: 'added-kg', text: 'Build to the heaviest clean set of 5' },
        progression: 'Estimated 1RM = 5RM load x 1.15. Record as % bodyweight. Lattice male standard is 165%.',
        protocolId: 'assessment',
        note: 'A 5RM is safer and almost as informative as a true single.',
        records: {
          benchmarkId: 'weighted-pullup',
          axis: { unit: 'kg', step: 1, min: 0, max: 80, prefix: '+', label: 'BEST 5RM, ADDED' },
          convert: 'five-rm-to-pct-bw',
        },
        form: {
          setup: 'Dead hang start, weight on a belt.',
          execution: 'Five strict reps, chin over bar, full extension each rep. Add weight and repeat until five is no longer clean.',
          cue: 'This is the number that tells you whether pulling strength is still limiting you. Under 165% total, it usually is.',
          breathing: 'Exhale on each pull.',
          mistakes: 'Counting reps that did not start from a dead hang.',
        },
      },
      {
        id: 'test-lockoff',
        name: 'TEST — 90 Degree Lock-Off',
        capacities: ['pull'],
        block: 'TEST', intensity: 'MAX',
        sets: 1, work: 30, unit: 'sec', restSec: 120,
        load: { kind: 'bodyweight', text: 'One arm, other hand lightly on the wrist' },
        progression: 'Enter the WEAKER side: that is the one that limits you. Solid is 10s, strong is 15s.',
        protocolId: 'assessment',
        perSide: true,
        records: {
          benchmarkId: 'lockoff-90',
          axis: { unit: 's', step: 1, min: 0, max: 60, prefix: '', label: 'WEAKER SIDE' },
          convert: 'identity',
        },
        form: {
          setup: 'Pull to 90 degrees of elbow flexion on one arm, free hand resting on the wrist.',
          execution: 'Hold until the elbow angle opens past 90. Time both sides and note the difference.',
          cue: 'A large left-right gap is worth training out. Climbers accumulate asymmetry without noticing.',
          breathing: 'Keep breathing.',
          mistakes: 'Pulling with the assisting hand.',
        },
      },
      {
        id: 'test-front-lever',
        name: 'TEST — Front Lever Hold',
        capacities: ['tension'],
        block: 'TEST', intensity: 'MAX',
        sets: 1, work: 30, unit: 'sec', restSec: 120,
        load: { kind: 'bodyweight', text: 'Hardest progression with a flat lower back' },
        progression: 'Enter the hardest progression held a clean 10s: 1 tuck, 2 advanced tuck, 3 one-leg, 4 straddle, 5 full. 0 if none yet.',
        protocolId: 'assessment',
        records: {
          benchmarkId: 'front-lever',
          axis: { unit: 'LVL', step: 1, min: 0, max: 5, prefix: '', label: 'PROGRESSION HELD 10S' },
          convert: 'identity',
        },
        form: {
          setup: 'Straight arms on a bar.',
          execution: 'Hold your hardest clean progression to failure of position, not failure of grip.',
          cue: 'The moment the lower back arches, the test is over. Arching is how people fake this hold.',
          breathing: 'Short controlled breaths.',
          mistakes: 'Recording a time that included five arched seconds.',
        },
      },
      {
        id: 'test-hip-mobility',
        name: 'TEST — Foot Raise + Straddle',
        capacities: ['mobility'],
        block: 'TEST', intensity: 'MODERATE',
        sets: 1, work: 120, unit: 'sec', restSec: 30,
        load: { kind: 'bodyweight', text: 'No load' },
        progression: 'Enter the WEAKER side foot raise in cm. Note the straddle separately. Average foot raise is about 74cm.',
        protocolId: 'assessment',
        records: {
          benchmarkId: 'hip-footraise',
          axis: { unit: 'cm', step: 1, min: 30, max: 130, prefix: '', label: 'FOOT RAISE, WEAKER' },
          convert: 'identity',
        },
        form: {
          setup: 'Stand next to a wall with a tape measure. Then sit into a maximal straddle with legs straight and feet flat.',
          execution: 'Raise one foot as high as possible with the hip flexed, abducted and externally rotated, knee bent. Measure floor to heel. Both sides. Then measure the straddle.',
          cue: 'Combined abduction and external rotation is what makes high steps, drop knees and bridging available. It is cheap to train and costs no recovery.',
          breathing: 'Relaxed, exhale into end range.',
          mistakes: 'Leaning the torso away to fake height. Not testing both sides.',
        },
      },
    ],
  },
  {
    id: 'cave-05', circuitNum: '05',
    title: 'ADD-ON', subtitle: 'after bouldering - pull - core',
    focus: 'One heavy pull, the one-arm path, the antagonists, then the trunk that keeps the feet on.',
    capacities: ['pull', 'press', 'legs', 'tension'],
    illustration: 'dumbbell.svg',
    duration: 45,
    recoveryHours: 12,
    stacksOnSession: true,
    note:
      'Runs straight after a boulder session, while you are already warm. No finger '
      + 'loading: the bouldering was the finger session. Pulling first while there is '
      + 'something left, then the patterns climbing never trains, then the trunk. If you '
      + 'are too cooked, pick TIRED: it keeps the pull, the press, the squat, the core '
      + 'and the cuff, and drops the TRX work.',
    exercises: [
      {
        id: 'addon-weighted-pullup',
        name: 'Weighted Pull-Ups',
        capacities: ['pull'],
        block: 'SECONDARY', intensity: 'HARD',
        sets: 3, work: 4, unit: 'reps', restSec: 150,
        load: { kind: 'added-kg', text: 'RPE 8 — two reps in reserve. You are pre-fatigued, so go lighter than you think.' },
        progression:
          'Bodyweight sets of 4 first. Once four sets of four are easy, start adding '
          + '2kg at a time. This is the lift that carries a one-arm pull-up for the '
          + 'first year: a two-arm pull-up with about half your bodyweight added is '
          + 'roughly the strength of one one-arm rep.',
        protocolId: 'max-strength',
        // SECONDARY, not PRIMARY: level adds no sets here. The fresh,
        // level-scaled weighted pull-up is in CAVE 01 and HOME 02; after two
        // hours of bouldering, extra sets buy fatigue rather than strength.
        variations: [
          { minLevel: 1, name: 'Pull-Ups — Bodyweight', load: 'Bodyweight, 4 clean reps, stop well short of failure' },
          { minLevel: 2, name: 'Pull-Ups — 4s Eccentric', load: 'Bodyweight, four seconds down' },
          { minLevel: 4, name: 'Weighted Pull-Ups', load: 'Belt or pack, RPE 8' },
          { minLevel: 6, name: 'Weighted Pull-Ups — Heavy', load: '+20% bodyweight or more' },
        ],
        form: {
          setup: 'Full dead hang, pronated grip just outside shoulder width. Harness and plates for the weighted version.',
          execution: 'Pull elbows down and back, chest leading, chin clearly over. Lower under control to a complete dead hang every rep.',
          cue: 'Four reps means four good reps. After bouldering you have less than you think, and a grinding fifth rep buys nothing.',
          breathing: 'Exhale on the pull.',
          mistakes: 'Treating this as a finisher to burn out on. It is a strength set that happens to come late in the day.',
        },
      },
      { ...oneArmShrug('addon-oap-shrug'), sets: 1 },
      assistedOneArm('addon-oap-assisted', 'addon-oap-path', 'pulley'),
      {
        id: 'addon-pushup',
        name: 'Push-Ups / Ring Dips',
        capacities: ['press', 'shoulder'],
        block: 'SECONDARY', intensity: 'MODERATE',
        sets: 3, work: 10, unit: 'reps', restSec: 90,
        load: { kind: 'bodyweight', text: 'Bodyweight. Add a pack or a belt once three sets of twelve are easy.' },
        progression:
          'Reps to 12 across all three sets, then move up the variation ladder before '
          + 'you add any weight. Range before load on a pressing pattern you have barely trained.',
        protocolId: 'strength-endurance',
        note: 'Wrists sore: push-ups on fists, dumbbells or push-up handles, so the wrist stays straight. Rings and dips already keep it neutral.',
        variations: [
          { minLevel: 1, name: 'Push-Ups' },
          { minLevel: 2, name: 'Ring Push-Ups' },
          { minLevel: 4, name: 'Ring Dips' },
          { minLevel: 6, name: 'Weighted Ring Dips', load: 'Belt or pack, RPE 8' },
        ],
        form: {
          setup: 'Push-ups: hands under the shoulders, body one straight line from heels to crown. Rings: set just above floor height, shoulders packed down. Dips: rings at hip height, arms locked, ribs down.',
          execution: 'Lower with the elbows tracking back at about 45 degrees from the ribs, chest to the floor or to the rings, then press to full lockout. On rings, finish each rep by turning the rings out until the palms face forward.',
          cue: 'Climbing is two hours of pulling and zero pressing, and the shoulder pays for that imbalance long before the fingers do. This is the single most useful thing in the session even though it feels like the least climbing-specific.',
          breathing: 'Inhale down, exhale on the press.',
          mistakes: 'Hips sagging. Elbows flaring to 90 degrees. On dips, dropping below the point where the shoulder stays packed - a deep dip loads the front of the shoulder hard and is not worth the extra range. Chasing the harder ring variation before the easier one is clean.',
        },
      },
      {
        id: 'addon-goblet-squat',
        name: 'Goblet Squat',
        capacities: ['legs'],
        block: 'SECONDARY', intensity: 'MODERATE',
        sets: 2, work: 10, unit: 'reps', restSec: 90,
        load: { kind: 'added-kg', value: 12, text: 'Kettlebell or dumbbell at the chest. Bodyweight until the depth is honest.' },
        progression:
          'Full depth with a flat back for two sets of twelve first. Then a 3s pause in '
          + 'the hole, then a heavier bell. Legs recover fast - this is the one place in '
          + 'the programme you can be impatient.',
        protocolId: 'strength-endurance',
        variations: [
          { minLevel: 1, name: 'Bodyweight Squat' },
          { minLevel: 2, name: 'Goblet Squat' },
          { minLevel: 4, name: 'Goblet Squat — 3s Pause' },
          { minLevel: 6, name: 'Goblet Squat — Heavy' },
        ],
        form: {
          setup: 'Feet shoulder-width, toes turned slightly out. Bell held at the chest by the horns, elbows inside the knees.',
          execution: 'Sit down between the hips until the hip crease passes the knee, chest tall, heels planted. Drive up through the whole foot. The bell at the chest is what lets you stay upright.',
          cue: 'Climbers get strong at pulling and at one-legged rockovers and stay weak at loaded knee flexion. Two sets is a maintenance dose that costs you nothing on the wall tomorrow.',
          breathing: 'Big breath in at the top, brace, exhale on the way up.',
          mistakes: 'Cutting depth to move weight. Heels lifting - park them on a 2cm plate if the ankles are stiff. Knees collapsing inward. Rounding the lower back at the bottom.',
        },
      },
      {
        id: 'addon-mountain-climber',
        name: 'Spiderman + Cross-Body Mountain Climber',
        capacities: ['tension'],
        block: 'SECONDARY', intensity: 'MODERATE',
        sets: 3, work: 16, unit: 'reps', restSec: 60,
        load: { kind: 'bodyweight', text: 'Bodyweight. Slow, hips at plank height' },
        progression:
          'Sixteen slow reps with level hips on every set, then a two-second hold at each '
          + 'elbow, then feet in the TRX straps.',
        protocolId: 'dynamic-core',
        note:
          'One rep is one knee: to the same elbow, back, to the opposite elbow, back. '
          + 'Alternate legs. Wrists sore: plank on fists or dumbbell handles, or drop to the forearms.',
        variations: [
          { minLevel: 1, name: 'Spiderman + Cross-Body Mountain Climber' },
          { minLevel: 3, name: 'Spiderman + Cross-Body, 2s Holds' },
          { minLevel: 5, name: 'TRX Spiderman + Cross-Body', load: 'Feet in the TRX straps, hands on the floor or on handles' },
        ],
        form: {
          setup: 'High plank, hands under the shoulders, body straight heels to head, glutes on. For the wrists: fists, dumbbells on their sides, or forearms. TRX version: toes in the foot cradles at mid-shin height.',
          execution: 'Draw the right knee outside the right arm toward the right elbow, return, then under the body toward the left elbow, return. Then the left leg. Hips stay at plank height and level throughout.',
          cue: 'This is the feet-on move: the hips and lower abs pulling a knee up and in while the arms hold. Outside the arm is a high step with the hip open; across the body is a drop-knee. Slow, it is not cardio.',
          breathing: 'Exhale as the knee comes in.',
          mistakes: 'Going fast and bouncing. Hips piking up or sagging. Shoulders drifting behind the hands. Bent wrists grinding through pain when a fist would do.',
        },
      },
      {
        id: 'addon-hanging-oblique',
        name: 'Hanging Oblique Knee Raise',
        capacities: ['tension'],
        block: 'SECONDARY', intensity: 'HARD',
        sets: 2, work: 8, unit: 'reps', restSec: 90,
        load: { kind: 'bodyweight', text: 'Bodyweight. Ab straps if the grip or fingers complain.' },
        progression:
          'Eight controlled reps with no swing on both sets, then half wipers with bent '
          + 'knees, then full windshield wipers.',
        protocolId: 'dynamic-core',
        note: 'Left plus right is 2 reps. Kept to two sets on purpose while the fingers are symptomatic.',
        variations: [
          { minLevel: 1, name: 'Hanging Oblique Knee Raise' },
          { minLevel: 4, name: 'Half Windshield Wiper', load: 'Knees bent, legs up at the bar, rotate side to side' },
          { minLevel: 6, name: 'Windshield Wiper', load: 'Legs straight at the bar, rotate side to side' },
        ],
        form: {
          setup: 'Hang from a bar, shoulders engaged, not passive. After bouldering, elbow slings or ab straps take the fingers out of it: the exercise is the trunk, not the grip.',
          execution: 'Draw both knees up and across toward one shoulder, lower under control, then the other side. Wipers: legs up at the bar, lower them to one side, return through the top, then the other side.',
          cue: 'Hörst calls wipers his favourite climbing core exercise: it is the position of cutting loose and getting the feet back on while hanging from the hands.',
          breathing: 'Exhale as the knees come up.',
          mistakes: 'Swinging to generate the lift. Dead shoulders. Grinding through a finger that is complaining when straps would remove it.',
        },
      },
      {
        id: 'addon-trx-core',
        name: 'TRX Body Saw / Pike',
        capacities: ['tension'],
        block: 'ACCESSORY', intensity: 'MODERATE',
        sets: 2, work: 10, unit: 'reps', restSec: 60,
        load: { kind: 'bodyweight', text: 'Feet in the TRX straps' },
        progression: 'Ten clean reps on every set, then the next variation. Body saw range grows before the pike.',
        protocolId: 'dynamic-core',
        note: 'The body saw is on the forearms, so it spares the wrists. On the tuck and pike, use fists or handles if the wrists are sore.',
        variations: [
          { minLevel: 1, name: 'TRX Body Saw', load: 'Forearm plank, feet in the straps' },
          { minLevel: 3, name: 'TRX Knee Tuck', load: 'High plank, feet in the straps' },
          { minLevel: 5, name: 'TRX Pike', load: 'High plank, feet in the straps, hips to the ceiling' },
        ],
        form: {
          setup: 'Straps at mid-shin height, toes in the foot cradles. Body saw: forearm plank. Tuck and pike: high plank, hands under the shoulders.',
          execution: 'Body saw: rock the body back past the elbows and return, ribs down. Tuck: knees to the chest. Pike: hips straight up, legs straight, feet sliding toward the hands.',
          cue: 'Straps make the feet unstable, which is exactly what a steep foothold is. Anti-extension keeps the hips from sagging; the tuck and pike pull the feet toward the hands.',
          breathing: 'Exhale on the pull-in.',
          mistakes: 'Lower back sagging on the body saw. Swinging the straps. Letting the shoulders drift behind the hands.',
        },
      },
      {
        id: 'addon-cuff',
        name: 'Band External Rotation',
        capacities: ['shoulder'],
        block: 'PREHAB', intensity: 'EASY',
        sets: 2, work: 15, unit: 'reps', restSec: 45,
        load: { kind: 'band', text: 'Light band — never to failure' },
        progression: 'Reps to 20, then a marginally heavier band.',
        protocolId: 'prehab',
        perSide: true,
        form: {
          setup: 'Band at elbow height, elbow tucked to the ribs at 90 degrees.',
          execution: 'Rotate the forearm outward keeping the elbow pinned, slow return.',
          cue: 'Two minutes. Do it on the way out of the gym.',
          breathing: 'Exhale rotating out.',
          mistakes: 'Skipping it because the session is nominally over.',
        },
      },
    ],
    substitutes: [oneArmPath('addon-oap-path')],
  },
  {
    id: 'cave-06', circuitNum: '06',
    title: 'FEET', subtitle: 'after bouldering - slab - tension',
    focus: 'Stand on nothing, keep the feet on steep ground: footwork, balance and the tension behind it.',
    capacities: ['legs', 'tension', 'mobility'],
    illustration: 'squats.svg',
    duration: 45,
    recoveryHours: 12,
    stacksOnSession: true,
    note:
      'Runs straight after a boulder session, the alternative to ADD-ON. The wall drills '
      + 'come first while you are still coordinated; pick problems far below your limit. '
      + 'Almost nothing here loads the fingers, so it is the add-on to pick on a day they '
      + 'are complaining.',
    exercises: [
      {
        id: 'feet-silent-laps',
        name: 'Silent Feet',
        capacities: ['legs'],
        block: 'PRIMARY', intensity: 'TECHNIQUE',
        sets: 3, work: 60, unit: 'sec', restSec: 60,
        load: { kind: 'bodyweight', text: 'Easy vertical or slab problems, 3-4 grades below your limit' },
        fixed: true,
        progression: 'Smaller footholds, then steeper ground, then a grade harder. Never faster.',
        protocolId: 'footwork-drill',
        note: 'Look at the hold, place the foot once, silently. No readjusting, no scraping.',
        form: {
          setup: 'An easy wall with small footholds. Climb up, across or down continuously for the minute.',
          execution: 'Watch each foothold until the shoe is on it. Place the exact spot you picked, first time, with no sound. The foot stays where it landed until it moves to the next hold.',
          cue: 'Weight the standing foot fully, then the moving foot is free to hover and place slowly. A loud foot is a foot that was placed by hope.',
          breathing: 'Slow, through the nose. Calm feet start with a calm body.',
          mistakes: 'Climbing too hard to be precise. Looking away before the foot lands. Shuffling the foot after it is placed.',
        },
      },
      {
        id: 'feet-fewer-hands',
        name: 'Fewer Hands Slab',
        capacities: ['legs', 'mobility'],
        block: 'PRIMARY', intensity: 'TECHNIQUE',
        sets: 3, work: 60, unit: 'sec', restSec: 60,
        load: { kind: 'bodyweight', text: 'The easiest slab in the gym' },
        fixed: true,
        progression: 'Two hands, then one hand, then no hands, then onto vertical ground where the margin is smaller.',
        protocolId: 'footwork-drill',
        note: 'Low to the mat. The point is to feel where the hips must be to stand on a foot.',
        variations: [
          { minLevel: 1, name: 'One-Hand Slab', load: 'One hand only, then the other' },
          { minLevel: 3, name: 'No-Hands Traverse', load: 'Hands behind the back, traverse low' },
          { minLevel: 5, name: 'No-Hands Slab', load: 'Hands off, up the easiest slab' },
        ],
        form: {
          setup: 'An easy slab or low-angle wall, a thick mat, feet never more than a metre up for the no-hands versions.',
          execution: 'Move up or across using as few hands as the version allows. Step through deliberately, weight shifting fully onto each foot before the next moves.',
          cue: 'Hips over the foot and away from the wall. On a slab the heel drops and the knee bends: the more you lean in, the less the rubber holds.',
          breathing: 'Exhale as you stand up onto a foot.',
          mistakes: 'Hugging the wall. Rushing the weight shift. Going high without hands.',
        },
      },
      {
        id: 'feet-steep-walk',
        name: 'Steep Foot Walk',
        capacities: ['tension'],
        block: 'SECONDARY', intensity: 'MODERATE',
        sets: 3, work: 30, unit: 'sec', restSec: 90,
        load: { kind: 'bodyweight', text: 'Jugs only on the steepest wall' },
        progression: 'Smaller and further footholds, then fixed feet with moving hands, then controlled foot cuts.',
        protocolId: 'tension-iso',
        note: 'Hands stay on big holds. The feet do the work: they move, and they pull.',
        variations: [
          { minLevel: 1, name: 'Steep Foot Walk', load: 'Hands on two jugs, walk the feet across many footholds' },
          { minLevel: 3, name: 'Fixed Feet, Moving Hands', load: 'Feet on two footholds, move the hands between jugs' },
          { minLevel: 5, name: 'Foot Cut and Re-Place', load: 'Cut both feet, swing still, put them back silently on the same holds' },
        ],
        form: {
          setup: 'Two jugs on steep ground, lots of footholds within reach. Arms long, not locked off.',
          execution: 'Walk the feet from hold to hold for 30 seconds, never letting one come off by accident. Higher versions: keep the feet planted while the hands move, or cut and re-place them.',
          cue: 'Pull with the toes as if dragging the foothold toward you, and push the hips into the wall. On steep ground a foot stays on because it pulls, not because it rests.',
          breathing: 'Keep breathing, especially as the foot moves.',
          mistakes: 'Hanging off bent arms. Resting the foot on the hold instead of pulling. Letting the hips sag away from the wall.',
        },
      },
      {
        id: 'feet-toe-hook',
        name: 'Toe-Hook Hold',
        capacities: ['tension'],
        block: 'SECONDARY', intensity: 'MODERATE',
        sets: 2, work: 8, unit: 'sec', restSec: 90,
        load: { kind: 'bodyweight', text: 'Big hold or volume, hands on jugs' },
        perSide: true,
        progression: '8 then 10 seconds, then one hand off, then a smaller hold to hook.',
        protocolId: 'tension-iso',
        form: {
          setup: 'Steep wall. Hands on two jugs, one toe hooked over a big hold or volume at about hip or hand height.',
          execution: 'Take weight into the hook: flex the toe up and pull the heel toward the shin, then hold. Both sides.',
          cue: 'The whole leg stays rigid. Relax it by a fraction and the toe slides off: that is what happens on the real problem.',
          breathing: 'Controlled.',
          mistakes: 'A floppy knee. Holding with the arms and letting the toe just touch.',
        },
      },
      {
        id: 'feet-edge-calf-raise',
        name: 'Toe-Tip Edge Calf Raise',
        capacities: ['legs'],
        block: 'SECONDARY', intensity: 'MODERATE',
        sets: 3, work: 8, unit: 'reps', restSec: 90,
        load: { kind: 'added-kg', value: 0, text: 'Climbing shoes on a small foothold, then a dumbbell in the same-side hand' },
        perSide: true,
        progression: 'Eight slow reps a side, then a smaller foothold, then a dumbbell.',
        protocolId: 'foot-strength',
        note: 'Three seconds down, heel below the hold, rise all the way onto the toe tip.',
        form: {
          setup: 'In climbing shoes, one foot on a small foothold or step edge, big toe on the hold, the other foot free. One finger on the wall for balance, no more.',
          execution: 'Lower the heel below the hold over three seconds, then press up until the ankle is fully extended and you are standing on the tip of the toe. Hold one second.',
          cue: 'This is standing on a tiny hold: pressure through the big toe, ankle stiff, the calf holding the position. The top of each rep is the part that matters.',
          breathing: 'Exhale on the way up.',
          mistakes: 'Rolling onto the outside of the foot. Bouncing out of the bottom. Pulling on the wall with the hand.',
        },
      },
      {
        id: 'feet-star-reach',
        name: 'Single-Leg Star Reach',
        capacities: ['legs'],
        block: 'SECONDARY', intensity: 'EASY',
        sets: 2, work: 30, unit: 'sec', restSec: 30,
        load: { kind: 'bodyweight', text: 'In climbing shoes, on a low foothold or a box edge' },
        perSide: true,
        progression: 'Floor, then a foothold, then eyes closed for the last 10 seconds.',
        protocolId: 'balance',
        form: {
          setup: 'Stand on one foot on a low foothold or the edge of a box, knee soft, hips level.',
          execution: 'Reach the free foot slowly forward, to the side, behind and across, touching down nothing, returning to centre each time. Thirty seconds, both sides.',
          cue: 'Stab at imaginary footholds with the free toe, quietly and precisely, while the standing foot holds still. This is a slab move without the wall.',
          breathing: 'Slow and even.',
          mistakes: 'Hip dropping on the free side. Locking the standing knee. Grabbing the wall at the first wobble.',
        },
      },
      {
        id: 'feet-rockover',
        name: 'Rock-Over Step-Up',
        capacities: ['legs', 'mobility'],
        block: 'SECONDARY', intensity: 'MODERATE',
        sets: 2, work: 5, unit: 'reps', restSec: 90,
        load: { kind: 'added-kg', value: 0, text: 'Box at knee height or higher, then a dumbbell in each hand' },
        perSide: true,
        progression: 'A higher box, then the foot placed wider with the knee turned out, then dumbbells.',
        protocolId: 'max-strength',
        note: 'No push from the back foot. The top leg does all of it.',
        form: {
          setup: 'A box at knee height or higher. One foot on top, turned slightly out, knee tracking over the toes.',
          execution: 'Shift the chest over the high foot, then stand up on it with the back foot relaxed, toes only touching. Lower under control.',
          cue: 'This is the single-leg squat up the wall: rock the weight over the high foot before you push. Hips open, knee out.',
          breathing: 'Exhale as you stand.',
          mistakes: 'Springing off the back foot. The knee collapsing inward. Standing up before the weight is over the foot.',
        },
      },
      {
        id: 'feet-pike-compression',
        name: 'Seated Pike Compression',
        capacities: ['tension', 'mobility'],
        block: 'ACCESSORY', intensity: 'MODERATE',
        sets: 2, work: 10, unit: 'reps', restSec: 60,
        load: { kind: 'bodyweight', text: 'Seated, legs straight' },
        progression: 'Higher lifts, then a two-second hold at the top, then legs in a straddle.',
        protocolId: 'dynamic-core',
        form: {
          setup: 'Sit tall with the legs straight, hands on the floor beside the knees or further forward.',
          execution: 'Lift both heels off the floor by pulling the thighs up toward the chest, without leaning back. Lower slowly.',
          cue: 'Strength at the end of the hip range is what puts a high foot on, and keeps it on, when there is nothing to push against.',
          breathing: 'Exhale on the lift.',
          mistakes: 'Leaning back to fake the height. Bending the knees.',
        },
      },
      {
        id: 'feet-cossack',
        name: 'Cossack Squat',
        capacities: ['mobility', 'legs'],
        block: 'MOBILITY', intensity: 'EASY',
        sets: 2, work: 45, unit: 'sec', restSec: 15,
        load: { kind: 'bodyweight', text: 'Bodyweight, hands on a post if needed' },
        perSide: true,
        progression: 'Deeper, then without a hand, then a light plate held at the chest.',
        protocolId: 'mobility',
        form: {
          setup: 'Wide stance, toes turned slightly out.',
          execution: 'Sit down over one leg while the other stays straight with its toes to the ceiling. Hold the bottom, then slow reps for the time. Both sides.',
          cue: 'Loaded adductor range is what lets the hips open on a slab and in a bridge. Work where it is uncomfortable, never sharp.',
          breathing: 'Exhale into the bottom.',
          mistakes: 'The bent-leg heel lifting. The chest collapsing forward.',
        },
      },
      {
        id: 'feet-frogger',
        name: 'Frogger + Active Straddle',
        capacities: ['mobility'],
        block: 'MOBILITY', intensity: 'EASY',
        sets: 2, work: 45, unit: 'sec', restSec: 15,
        load: { kind: 'bodyweight', text: 'No load' },
        progression: 'Knees wider, then the hips closer to the floor. Active lifts higher and longer.',
        protocolId: 'mobility',
        note: 'Set 1: frogger. Set 2: seated straddle, lift one straight leg then the other, 5 each.',
        form: {
          setup: 'Frogger: on the forearms, knees wide, inside edges of the feet on the floor. Straddle: seated, legs wide and straight.',
          execution: 'Frogger: rock the hips gently back and forward, sinking a little wider each time. Straddle: hands on the floor, lift one leg off the floor as high as possible and hold two seconds.',
          cue: 'Wide, flat-to-the-wall hips are what put the weight over the toes on a slab. Passive range makes it possible, active strength makes it usable.',
          breathing: 'Long exhales into the stretch.',
          mistakes: 'Forcing the range. Arching the lower back in the frogger.',
        },
      },
    ],
  },
];
